slidevjs/slidev

- docs/themes/gallery.md
- docs/themes/use.md
- docs/themes/write-a-theme.md
I fixed some typos and reformulated some sentences in the themes docs.
Feel free to pick and choose among the larger changes — some are a matter of taste.
> docs: improve some formulations in the themes documentation

- packages/client/internals/Editor.vue
Fixed code overlaps when open editor panel and slides overview.
Related issue #14.
> fix: codemirror overlaps, close #14

- docs/guide/why.md
A small typo on the "Why" page of the guide, "expirenice" -> "experience".
> Fix "experience" typo.

- CONTRIBUTING.md
- docs/custom/index.md
- docs/guide/install.md
- packages/types/src/types.ts
Fixed 2 typos:
1. Replacing occurrences of `stater` with `starter` 
2. Updating occurrences of `infomation` with `information`
> chore: fix typos

- packages/slidev/node/cli.ts
Currently, the dev server automatically opens a new browser tab/window when running `dev`, but this can be confusing to users (especially on MacOS, where it shuffles the windows around).
Also, it is currently not possible to opt out this effect.
Disabling it by default seems like the best solution to me, since users are not forced to use the immediate open functionality, but can still opt in to this behaviour using the `--open` flag.
> fix(cli): not open browser by default

- packages/client/internals/MenuButton.vue
- packages/client/internals/NavControls.vue
- packages/client/state/index.ts
Hi Anthony,
I noticed that you have fixed this issue. However, the same problem also occurs if my mouse does not leave the navigation bar. 
I think your solution is already perfect, just provide another solution for you to check. 😄 
Furthermore, I find that the total page number on the navigation bar is always 1 less than the actual one, and I fix it by adding 1. 😄
> fix(client): nav control focus (Triggered with next page/animation at the same time)

- demo/composable-vue/slides.md
- packages/slidev/node/plugins/fix.ts
- packages/slidev/node/plugins/markdown-it-prism.ts
- packages/slidev/node/plugins/markdown-it-shiki.ts
- packages/slidev/node/plugins/markdown.ts
I was actually thinking about recursive double brackets, but since I have never run into that in vue and other template languages, will leave it this way for now.
> fix(md): escape vue template with character references, close #99

- packages/client/builtin/Youtube.vue
As per the title, the usage of the Youtube component contains a typo.
> docs: fix a typo in the Youtube component usage

- docs/guide/syntax.md
With the v-bind `:id` prop, the Tweet component doesn't always work.
e.g.
`@antfu7`'s pinned tweet doesn't render with the prepending colon (:).
`<Tweet :id="1389800180002672641" />` doesn't work
but `<Tweet id="1389800180002672641" />` works.
Also, the closing `div` doesn't have slash, causing a server error.
> docs(syntax): fix the tweet component usage

- packages/client/logic/shortcuts.ts
Currently, keeping right pressed does nothing more than just pressing it once. The event should auto repeat if the key combination is still pressed. 
This PR is an untested work. I have not built slidev, I just wanted to try it out and ask if you thought it was a good idea. I actually modified the code in github's default, so it might not even build. If you think that the idea is worth a bit of work I will put it.
> feat: shortcuts auto repeating

- docs/.vitepress/themes.ts
Theme with bar bottom component to add slide title/note and social media.
NPM: https://www.npmjs.com/package/slidev-theme-purplin
GitHub: https://github.com/moudev/slidev-theme-purplin
> docs(themes): add Purplin theme

- packages/slidev/node/plugins/monaco.ts
btw looks like lock file is not up-to-date
> fix(slidev): monaco plugin type import path in windows os

- demo/starter/package.json
`pnpm demo:dev` cannot recreate a symbolic link at ubuntu-18.04.
```
pnpm demo:dev
> @0.13.10 demo:dev /home/solenoid/ghq/github.com/mikanIchinose/slidev
> pnpm -C demo/starter run dev
> @ dev /home/solenoid/ghq/github.com/mikanIchinose/slidev/demo/starter
> ln -sF ../../packages/create-app/template/slides.md slides.md && nodemon -w '../../packages/slidev/dist/*.js' --exec 'slidev ./slides.md --open=false --log=info'
ln: failed to create symbolic link 'slides.md': File exists
 ERROR  Command failed with exit code 1.
 ERROR  Command failed with exit code 1.
```
add option `-f` at `dev` script of  `demo/starter/packege.json`
> fix: forced create symbolic link

- packages/client/internals/Settings.vue
- packages/client/internals/SlideContainer.vue
- packages/client/state/index.ts
Fix #173 / #177.
Using `null` in number typed `slideScale` would also make Vue runtime type checking fail.
But notice this fix gives special meaning to value `0`, replacing the original `null`.
> fix: Non-number slideScale causing mispositioning

- packages/client/logic/nav.ts
Fix #179.
State `hasNext` and `hasPrev` are now aware of the clicks now.
> fix: complete state for hasNext and hasPrev

- packages/create-theme/template/styles/index.ts
`./styles/main.css` is required by the `create-theme` package, however, it was removed in [a prior commit](https://github.com/slidevjs/slidev/commit/e61c7f894065bc4b299048e737120eb15c6bcd68#diff-218165a8ed3169515a1607c50db704ce52c29489e2d5300dffb08204eb59febb).
This causes a Vite server error as it expects the main.css file. The proposed PR removes said import.
> fix: removing broken import in create-theme

- packages/parser/src/core.ts
- test/parser.test.ts
Example:
```markdown
---
title: One
---
---
title: Two
---
```
AST:
Prettier will format it to
```diff
---
title: One
---
---
-title: Two
----
+
+## title: Two
```
inspired by [section-matter](https://github.com/jonschlinkert/section-matter), add some text after the first `---`, Prettier will just add a blank line before the second `---`.
```diff
---
title: One
---
--- section 2
title: Two
+
---
```
> fix: support section matter

- packages/client/logic/shortcuts.ts
- packages/client/setup/shortcuts.ts
- packages/types/src/setups.ts
Fixes #209 
Add shortcuts configuration.
Create `./setup/shortcuts.ts` with the following content:
```ts
import { defineShortcutsSetup, NavOperations } from '@slidev/types'
export default defineShortcutsSetup((nav: NavOperations) => {
return [
{
key: 'enter',
fn: () => nav.next(),
autoRepeat: true,
},
{
key: 'backspace',
fn: () => nav.prev(),
autoRepeat: true,
},
]
})
```
Related type declaration:
```ts
export interface NavOperations {
next: () => void
prev: () => Promise<void>
nextSlide: () => void
prevSlide: () => Promise<void>
downloadPDF: () => Promise<void>
toggleDark: () => void
toggleOverview: () => void
escapeOverview: () => void
showGotoDialog: () => void
}
export interface ShortcutOptions {
key: string
fn: () => void
autoRepeat?: boolean
}
export type ShortcutsSetup = (nav: …
```
> feat: shortcuts configuration

- packages/client/builtin/Mermaid.vue
- pnpm-lock.yaml
Hi,
In the new scaling method introduced earlier, the mermaid SVG's original `height` attribute is used. However, in some cases, the SVG returned my mermaidjs has a `height` attribute equal to "100%" which makes the scaling non consistent.
Using the viewBox attribute of the SVG should solve this issue, since `height/viewBox[3]` can directly be interpreted as a scaling factor for the SVGs.
Thanks!
/CN
> fix: use viewBox attribute instead of height when scaling Mermaid diagrams

- packages/client/logic/shortcuts.ts
- packages/create-app/template/slides.md
- packages/create-theme/template/example.md
- packages/slidev/template.md
- packages/types/src/setups.ts
Hi, thanks for making Slidev! This was already brought up in #1. But as far as I understand this issue is not resolved yet. The commit https://github.com/slidevjs/slidev/commit/68b5d0658cc4a4cfc174607f700f794676140559 only added the <kbd>shift</kbd><kbd>left</kbd> and the <kbd>shift</kbd><kbd>right</kbd> shortcuts, but didn't implement switching to the previous slide using the proposed <kbd>shift</kbd><kbd>space</kbd> shortcut.
I tried to just add
```js
{ key: 'shift_space', fn: () => prevSlide(false), autoRepeat: true },
```
to
https://github.com/slidevjs/slidev/blob/8cce79a382ab8ad3ca26958ab68b52e07da4b410/packages/client/logic/shortcuts.ts#L43-L51
but this led to the problem that pressing <kbd>shift</kbd><kbd>space</kbd> also triggers the callback for <kbd>space</kbd>. As far as I …
> feat: add shift+space to move to the previous page

- cypress.json
- cypress/fixtures/basic/slides.md
- cypress/integration/examples/basic.spec.ts
- packages/client/builtin/VClick.ts
- packages/client/builtin/VClicks.ts
- packages/client/internals/SlideWrapper.ts
- packages/client/logic/nav.ts
- packages/client/modules/directives.ts
As I said in #272 .
I add a order map to record `v-click` order.
`orderMap` struct is:
```ts
orderMap: Map<number, HTMLElement[]>
```
Key is order `number`
Value is `HTMLElement` array
For `v-click` which not set their order, they will set their order as their index in `elements`.
The reason for using array as map value is for `v-after`.
When initialize one `v-after` element, it will push itself to the last of array.
Then, we can set the last item of array to `current` state, the others items to `prior` state.
This implement is better than the #271, it looks more elegant.
For simplfy `v-click-hide`, I add `hide` prop for `<v-click />`.
And I think it will be better the `v-click-hide` just call some thing like `<v-click hide />`, but don't know how to implement it.
Still, the state design …
> feat(v-click): use order map to order v-click

- .gitpod.yml
- CONTRIBUTING.md
This PR introduces a `.gitpod.yml` configuration file to enable ephemeral, browser-based development environments based on www.gitpod.io. It automates the [CONTRIBUTING.md](CONTRIBUTING.md) instructions and starts Slidev automatically with `pnpm demo:dev`
Until this PR is merged, please use the following button to test what the development environment experience will be like:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/mikenikles/slidev/tree/configure-automated-dev-environments)
The above button uses my own branch which has Gitpod Prebuilds configured. See the next session on how to enable that for `slidevjs/slidev` and why it is beneficial.
In order to get the best experience, the `slidevjs/slidev` repository will have to [enable …
> docs: configure automated development environments

- packages/slidev/node/plugins/config.ts
Missing Content-Type (`text/html`) will cause DevServer not works with domains, likes using public port forwardings on [GitHub Codespaces](https://github.com/features/codespaces).
> fix: add content-type for html files on dev server

- cypress/fixtures/basic/slides.md
- cypress/integration/examples/basic.spec.ts
- packages/client/modules/directives.ts
`v-click-hide` route not work, because `elements` has nothig.
Fix it as how `v-click` work.
Fix #323.
> fix(v-click-hide): the route for v-click-hide

- packages/slidev/node/cli.ts
Sometimes, the `slidev --open` shortcut command fails (such as browser not exist), and it causes the entire development server to fail.
I'm trying to add a catch statement to suppress this situation
> fix: catch cli open shortcut errors

- packages/types/src/config.ts
> chore: typo

- packages/slidev/node/cli.ts
Right now we need to press `r/o/e` and then press enter to perform the shortcut. It should be better to just perform the shortcut on keypress event
PS: While running dev server, we still need to press enter every time, since nodemon is also waiting for keys to be pressed (i.e. "rs" to restart server), we're running into a conflict because nodemon has commandeered process.stdin.
> feat: perform terminal shortcuts on keypress

- packages/client/setup/shortcuts.ts
- packages/types/src/setups.ts
Hi, 
I needed to create a shortcut to toggle drawings but current API didn't expose it. 
So in this PR i  exposed it through the NavOperations object. 
The changes seem fine to me, but i couldn't figure out how to test it locally. So if someone knows how to do that, please test this before merging the PR. 
Thanks !
> feat(shortcuts): expose toggleDrawing in NavOperations

- packages/slidev/node/plugins/extendConfig.ts
- packages/slidev/node/utils.ts
- packages/slidev/package.json
- pnpm-lock.yaml
Fix #409 
When global installed, resolve `@slidev/client` and `katex` from `__dirname`.
> fix: resolve global import

- packages/slidev/node/options.ts
#407 did not fully fix nested directory globally.
Because `entry` was a filename, and slidev cannot find `slides.md` correctly.
```ts
const data = await parser.load(entry) // entry -> 'slides.md'
```
> fix: make entry an absolute path

- packages/slidev/node/build.ts
Fixes the generated PDF when combining `download: true` and `routerMode: hash`.
The generated PDF contained n times the first page (here is an exemple: https://nlepage.github.io/build-userfriendly-cli-tool-talk/main/slidev-exported.pdf).
Thanks for the awesome project!
> fix: download with routerMode=hash

- packages/slidev/node/export.ts
Following #425
This one fixes the generated PDF file when building with `download: true`, `routerMode: hash`, and using a base path.
Tested the modifications with these four combinations:
- `routerMode: history` and `slidev build`
- `routerMode: history` and `slidev build --base /test/`
- `routerMode: hash` and `slidev build`
- `routerMode: hash` and `slidev build --base /test/`
> fix: PDF when build with download=true, routeMode=hash and a base path

- packages/client/layouts/iframe-left.vue
- packages/client/layouts/iframe-right.vue
- packages/client/layouts/iframe.vue
I found these were using an outdated syntax that imports `defineProps()`.
I had to keep `props` because it's not possible to do `:class="class"` as `class` is a reserved keyword
> refactor: use type based defineProps

- packages/parser/src/core.ts
- packages/slidev/node/plugins/markdown.ts
`trimRight` has been deprecated, we can use `trimEnd` instead of `trimRight`.
> refactor: use trimEnd instead of trimRight

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
- packages/client/logic/nav.ts
- packages/client/routes.ts
- packages/parser/src/core.ts
- packages/slidev/node/plugins/loaders.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
Adding a built-in TOC component.
TOC is really useful when you have long presentations (like for a 3 days training for example). It helps people not to be to much lost.
Lots of presentation library miss this feature, that is mandatory in the usage I have.
I found this library awesome, that's why I am proposing this feature, because It would even more incredible with this feature :smiley: 
This feature automatically gather informations about the title and the title level of each slides to build a tree.
You can also set both information using front matter syntax (if your slide does not contain a title, or if you want to override it).
For example:
```md
---
title: Amazing slide title
title level: 2
---
```
Available props for the Toc component:
* columns (default = 1): TOC in multiple …
> feat: add Toc component

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
It is not urgent, but I just realized I forgot to add the `slidev` prefix to HTML classes.
> fix: add 'slidev' class prefix

- packages/client/builtin/TocList.vue
- packages/parser/src/fs.ts
Typical use-case: having an image in the title.
```
// Or
```
(replaces https://github.com/slidevjs/slidev/pull/470 that has been auto-closed when renaming the source branch)
> feat: allow HTML in TOC

- packages/client/logic/recording.ts
Currently, when recording the presentation, the video is not recorded anymore after 1h delay. When the recording is stopped, the resulting video will never exceed 1h long.
[This issue](https://github.com/muaz-khan/RecordRTC/issues/144) explains why.
This PR increases the value to 24h, which should be enough for most use-cases.
> fix: extend 1h recording limit to 24h

- packages/client/internals/Goto.vue
Fixes https://github.com/slidevjs/slidev/issues/495
Rational of the changes.
To solve the appearing 'g' in Firefox
- I could only watch the `text` value and remove any leading non-digit (the 'g' arrives very late, clearing after nextTick() is not sufficient)
- as we want to have access to the exact typed value and also `text` is a ref<string>, I switched the input from number to text (the semantics is less good unfortunately)
- previous change makes the CSS unnecessary (it was un-styling the browser specific type=number input)
To solve the focus problem
- I explicitly blur the input when the dialog is hidden (move out of the view)
- to avoid doing two complementary whenever, I used a single watch
> fix: goto dialog containing g and not blurring in Firefox

- packages/slidev/node/options.ts
- packages/slidev/node/plugins/preset.ts
In some cases, I want to customize the state of server, such as drawing and sharing some data with other clients.
> feat: expose ServerRef state

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
Currently, using `<Toc />` merely offers a disc styled list but table of contents usually want numeric numbering.
With this PR, the `<Toc />` list style becomes configurable using the added prop `listStyle` which allows `decimal`and `disc` and defaults to `decimal`.
> feat: support specify `list-class` for TOC

- packages/client/builtin/Link.vue
- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
- packages/client/builtin/Tweet.vue
- packages/client/builtin/Youtube.vue
- packages/client/composables/useContext.ts
- packages/client/composables/useNav.ts
- packages/client/composables/useNavClicks.ts
- packages/client/constants.ts
- packages/client/internals/Print.vue
- packages/client/internals/PrintContainer.vue
- packages/client/internals/PrintSlide.vue
- packages/client/internals/PrintSlideClick.vue
- packages/client/logic/drawings.ts
- packages/client/logic/nav.ts
- packages/client/modules/context.ts
- packages/client/routes.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
- packages/slidev/node/plugins/loaders.ts
- packages/slidev/package.json
- pnpm-lock.yaml
This is currently a Work In Progress to try to solve the following issue https://github.com/slidevjs/slidev/issues/483
Currently this version adds a new route `/print` that displays all slides.
I created a new built-in `Link` component that uses anchor when we are in print mode.
When exporting to PDF, it uses the new route and the PDF is generated in one shot (no need to merge all pages together anymore).
Pros:
* Links works inside the PDF
* Big performance gain when generating the PDF (about 230 slides generated in 20 seconds against more than 11 minutes with the previous version)
Problems:
1. We need to rethink the nav logic because we can't rely on the global context to gives informations about `currentPage`...Etc.
Currently the `currentPage` is 1 when printing, but this causes issue …
> feat: print all slides into one page, fix link in pdf export 

- packages/parser/src/core.ts
- packages/parser/src/fs.ts
- test/__snapshots__/parser.test.ts.snap
- test/fixtures/markdown/multi-entries.md
- test/fixtures/markdown/sub/nested1-4.md
- test/fixtures/markdown/sub/pages3-4.md
This PR allows an md file included with `src: ....` to contain several slides and also to itself include another md file recursively (with no limit on the depth). I've added some tests, limited to two levels: a src that contains a src (that itself contains several slides).
Given that the slides are now parsed, a few things change in the result (notes are parsed, `title:` frontmatter get added, ...).
A possible ugliness in the proposed implementation is that the frontmatter (that originally contains `src`) is rewritten as `srcseq` to keep track of the nested includes, as in https://github.com/slidevjs/slidev/compare/main...twitwi:allow-multiple-slides-in-src?expand=1#diff-71214303b78b0f2ebd638a82b7608f2dc802d4e43f81895ca44bbcf66f3f5088R719
----
fixes: …
> feat: multiple slides and recursive include for multi-entries

- packages/client/builtin/Link.vue
- packages/client/builtin/TocList.vue
fixes https://github.com/slidevjs/slidev/issues/499
Also cleans up some empty TocList elements (I found it while working on the fix but I can do a second PR if needed)
More visually, the second commit removes the TocList-s between the Link-s
> fix: blur router links to give back the focus to the slides

- packages/client/builtin/Tweet.vue
This PR shows an error message when the tweet cannot be loaded (createTweet return undefined).
Also, we avoid waiting for the iframe in this case, which was blocking the pdf export in this case.
Solves my last comment to https://github.com/slidevjs/slidev/issues/397
> fix: handle case of wrong tweet id, avoid blocking pdf export

- packages/client/internals/Goto.vue
- packages/client/logic/nav.ts
- packages/slidev/node/plugins/loaders.ts
Currently working with with internal links only, i.e. in a `<Link to="..." />` but not as a bookmark (visiting directly the page), no idea why...
> feat: allow routeAlias frontmatter to be able to link to slides by name

- cypress/integration/examples/basic.spec.ts
Ref #591 and https://github.com/slidevjs/slidev/pull/591#discussion_r879042611
Accidentally deleted the basic up cypress test assert, bring it back in this PR.
> fix(cypress): bring basic UpArrow assert back

- packages/client/internals/NavControls.vue
- packages/client/internals/Presenter.vue
- packages/client/internals/VerticalDivider.vue
- packages/client/styles/index.css
Fixes https://github.com/slidevjs/slidev/issues/615
Propsals:
Mobile landscape:
Mobile portrait:
Tablet landcape:
Tablet portrait:
Desktop:
* add one column display when width << height
* use previous mobile display (2 cols) when width < height
* use classique display (3 cols) when width > height
* add context information ("current" and "next")
* try to fit the bottom bar in one line for small width
> feat: update presenter mode styles for mobile

- packages/client/setup/shortcuts.ts
- packages/types/src/setups.ts
When users want to extend the existing shortcuts (which are very minimal) with the customized setup then they still should be able to easily access some core navigation elements.
This PR exposes the `go()` navigation control.
> feat: expose go() for dynamic slide navigation

- packages/client/builtin/CodeBlockWrapper.vue
- packages/client/styles/code.css
**Related Issue(s)**
https://github.com/slidevjs/slidev/issues/378
**Why**
It enables automatically scrolling to the current highlighted code, by setting maxHeight option on code block.
**Example:**
```
```ts {all|2|1-6|9|all} {height:'200px'}
interface User {
id: number
firstName: string
lastName: string
role: string
}
interface User2 {
id: number
firstName: string
lastName: string
role: string
}
interface User3 {
id: number
firstName: string
lastName: string
role: string
}
interface User4 {
id: number
firstName: string
lastName: string
role: string
}
```
Video:
https://user-images.githubusercontent.com/46906474/177882902-a6bbcd4e-4029-4ff4-afb7-822e9ca3c15c.mp4
> feat: auto scroll code highlight, close #378

- packages/slidev/node/plugins/markdown.ts
- packages/slidev/package.json
- pnpm-lock.yaml
#640 
- Some popular packages were no longer maintained([markdown-it-task-lists 4 years ago](https://www.npmjs.com/package/markdown-it-task-lists), [markdown-it-task-checkbox  4 years ago](https://www.npmjs.com/package/markdown-it-task-checkbox)) and they were not pass the syntax check. This package (https://github.com/hedgedoc/markdown-it-better-task-lists) got a quick release after I fixed a rendering bug. It appears to be maintained by an organization.
- It's written in TS and has unit tests.
- I set `enable` option to `true`. It's more beautiful but is unlike Github Style.
- The plugin options can't be set outside. I'm not sure what effect it will have on historical compatibility.
> feat: Github style checkbox

- packages/client/internals/Presenter.vue
This prevents width changes in the timer numbers which causes unnecessary movement and distraction
> feat: change timer on presenter view to use tabular nums

- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
This adds a `export --chrome-executable` CLI parameter to override the bundled chrome coming with playwright.
I use this to export my slides with the chrome provided by my system, as the playwright chrome build is not binary compatible (I use nix for building, but this would also apply for a musl based system like alpine linux.)
> feat: add chrome-executable parameter to export

- packages/slidev/node/plugins/extendConfig.ts
- packages/slidev/node/plugins/loaders.ts
修复 #679 
问题原因：
`Symbol` 惹的祸
全局属性 `$slidev` 的注入名声明在 `packages/client/constants.ts`，为 `Symbol`，其提供于文件 `packages/client/modules/context.ts`，注入于插件 `slidev:layout-transform:pre` `slidev:context-transform:pre` 。
开发环境下，上述两插件中的依赖项会预编译到 `node_modules/.vite/deps`，即，`constants.ts` 暂存位置。提供处仍引用的是 `packages/client/constants.ts`。
此时出现了两份 `constants.ts`，而 Symbol('slidev-slidev-context') !== Symbol('slidev-slidev-context')，故而报错。
解决办法：
分别配置两插件，在预构建中强制排除依赖项 `@slidev/client/constants`。
> fix: $slidev injection, close #679

- packages/client/logic/shortcuts.ts
- packages/client/setup/shortcuts.ts
- packages/slidev/node/plugins/setupClient.ts
Fixes https://github.com/slidevjs/slidev/issues/629
IMPORTANT, There are 4 commits
- the 1st one is the core feature, probably without big issues,
- the 2nd one is an (optional but that I find nice) refactoring,
- the 3rd one is **to be discussed** (or just dropped) as it is a **breaking change** and would necessarily require a documentation update (that would be highly recommended anyways even with the first commits).
- following the discussion commit 4 adds a user message to help migration
Basically, the third commit breaks every situation that used setup/shortcuts (the default shortcuts are then removed).
The doc update would suggest something like:
```ts
export default defineShortcutsSetup((nav: NavOperations, baseShortcuts: any) => {
return [
...baseShortcuts,
{
```
Related to …
> feat!: injection chains to allow merging custom and addons/themes keyboard shortcuts

- packages/parser/src/config.ts
- packages/parser/src/core.ts
- packages/slidev/node/build.ts
- packages/slidev/node/drawings.ts
- packages/slidev/node/options.ts
- packages/slidev/node/server.ts
Initially, persistent drawings were stored in the same dir for the whole project.
Using multiple different entry slides was leading to overriding drawings.
> feat!: separate persistent drawing dirs per entry slides

- demo/starter/pages/hidden.md
- demo/starter/pages/multiple-entries.md
- demo/starter/slides.md
- packages/parser/src/fs.ts
Optionally hide subpages via `hide: true`. The `starter` demo slides now reflect this new functionality.
Example:
```markdown
---
src: ./subpage2.md
hide: true
---
```
In this example, `./subpage2.md` is skipped. This:
- doesn't generate any extra slide
- doesn't forget about any other slide in the deck
- keeps `$slidev.nav.currentPage` and `$slidev.nav.total` consistent, as if the markdown block above was never defined in the first place.
Closes https://github.com/slidevjs/slidev/issues/720.
TODO:
> feat: optionally hide subpages

- packages/client/layouts/two-cols-header.vue
I was missing this layout, since it's one I use a lot:
In slidev, it looks like this:
> feat: add layout of two columns with a header (two-cols-header)

- packages/create-app/template/vercel.json
Changes the default `vercel.json` file from
```json
{
"rewrites": [
{ "source": "/(.*)", "destination": "/index.html" }
],
}
```
to
```json
{
"rewrites": [
{ "source": "/(.*)", "destination": "/index.html" }
],
"buildCommand": "npm run build",
"outputDirectory": "dist"
}
```
Closes https://github.com/slidevjs/slidev/issues/722.
> fix(vercel): fix build outputs configuration

- .gitignore
- packages/create-app/build.mjs
- packages/create-app/package.json
Here is the thing:
- package `create-app` invoke build
- build command copy files
but ../../demo/starter/slides.md includes ../../demo/starter/pages/multiple-entries.md:
So we must copy `multiple-entries.md` when build.
I create a script to do this work.
Hope will fix this issue :)
> fix: create app template error

- packages/client/layouts/image-left.vue
- packages/client/layouts/image-right.vue
Hello, 
I noticed that the size of the full height images in the `image-left` and `image-right` template changes depending on the size of the opposite column. This can be seen in the first image, where the left column is slightly larger than the parent slide. This automatically enlarges the image column as well.
This can look off, when two `image-right` or two `image-left`-slides are used immediately after another with the same default image. The slide that has overflowing content, will show a more zoomed in image (image1) than the one without overflow (image2).
This pr changes the two columns to be only as heigh as the parent slide, e.g. eliminating overflow content.
There are also other options like absolute positioning, if the content should be able to overflow the content without …
> fix(layouts): prevent overflow in `image-left` and `image-right` layouts

- packages/client/composables/useNav.ts
- packages/client/logic/nav.ts
When no layout is explicitly configured, the currentLayout value is empty. There are actually two possibilities, `cover` and `default`.
> fix: currentLayout will no longer be empty

- packages/parser/src/core.ts
- packages/parser/src/fs.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/plugins/setupNode.ts
- packages/types/src/setups.ts
- packages/types/src/types.ts
- test/parser.test.ts
Targeting https://github.com/slidevjs/slidev/issues/700
I think the core of the PR is fully ok (all parser tests still passing, more tests added for the extensibility).
The question of **clean integration in the project** is to be checked as I'm not fully familiar with its architecture.
> feat: support custom preparser

- packages/slidev/node/common.ts
- packages/slidev/node/options.ts
Depending on the extension point (setup/*), the addons were considered or not.
With this PR, now addons are considered in all places where themes are considered.
> fix: add missing use of addonRoots, e.g. for setup/katex.ts in addons

- packages/slidev/node/export.ts
In https://github.com/slidevjs/slidev/pull/669 `pdf-lib` dependency was added and an option to process exported PDF to add some info to it.
Why not go further and enhance exported PDF a little bit more, adding basic metadata to it?
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After (look at window title):</summary>
</details>
> feat(export): add basic metatada to exported PDF

- packages/parser/src/core.ts
- packages/parser/src/fs.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/plugins/setupNode.ts
- packages/types/src/types.ts
- test/parser.test.ts
The headmatter was not (always) properly parsed and not passed to the addons.
Now it is passed to the preparser addons (it can be useful to pass them configuration, or to provide a way to enable/disable certain features)
> fix: properly pass headmatter to the extensions

- packages/client/internals/PrintContainer.vue
- packages/slidev/node/export.ts
Currently `--range` is ignored in slidev export.
This especially prevents exporting huge presentations as they cannot even be exported by parts.
see https://github.com/slidevjs/slidev/issues/774
> fix: use provided range when exporting

- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
Fixes #795 
Added timeout arg to `export-note` command as in #542.
> fix(export): add timeout arg for export-notes command

- packages/parser/src/fs.ts
- test/__snapshots__/parser.test.ts.snap
- test/fixtures/markdown/multi-entries.md
- test/fixtures/markdown/sub/nested1-4.md
- test/parser.test.ts
For https://github.com/slidevjs/slidev/issues/753
Make includes relative to their containing file (e.g. when nesting includes inside includes) + allow a leading '/' to refer to the project root.
+ also improves/fixes preparser extensions (that were not applied to included files).
> feat: relative includes/imports/src:

- packages/client/builtin/TocList.vue
- packages/slidev/node/plugins/loaders.ts
This fix is related to https://github.com/slidevjs/slidev/issues/812
Because now markdown is not parsed anymore when wrapped in a component, the toc component does not render the parsed HTML of the original title, but renders the raw markdown (notice the ``What is `Slidev` ?``):
This fix the toc component like this (rendering the markdown of the title):
This PR may not be needed if https://github.com/mdit-vue/vite-plugin-vue-markdown/issues/14 is fixed
> fix: parse markdown in toc

- package.json
- packages/client/internals/SlidesOverview.vue
- packages/client/package.json
- pnpm-lock.yaml
Fixes https://github.com/slidevjs/slidev/issues/827
(issue in @vueuse/core has been fixed in this commit https://github.com/vueuse/vueuse/commit/ae78d8bda74f33d9db2d12aed07e277d6cd323ca)
> fix: active element

- packages/client/state/syncState.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/drawings.ts
- packages/slidev/node/options.ts
- packages/slidev/node/plugins/extendConfig.ts
- shim.d.ts
Fixes https://github.com/slidevjs/slidev/issues/692
Added a new global variable `__USE_SERVER__` and a new `"export"` mode:
* `mode="dev"` means `__DEV__=true` and `__USE_SERVER__=true`
* `mode="export"` means `__DEV__=false` and `__USE_SERVER__=true`
* `mode="build"` means `__DEV__=false` and `__USE_SERVER__=false`
I didn't forced the export to be in dev mode because in that mod we renders additionnal things like the Monaco editor...etc. we won't use in the export.
> fix: export drawings in export (if persist is true)

- packages/slidev/node/plugins/windicss.ts
Trying to build the project i ran into issues where windi `defaultConfigureFiles` was undefined.
Looking into the https://github.com/windicss/vite-plugin-windicss repo it appears the windi config files where moved to the `'@windicss/config'` package.
so changing to this appears to fix. 
```typescript
const { defaultConfigureFiles } = await import('@windicss/config')
```
> fix: update windicss import of default configure Files

- package.json
- packages/slidev/node/plugins/markdown.ts
- packages/slidev/package.json
- pnpm-lock.yaml
Both npm packages are marked as `deprecated`.
- `@types/mermaid` - no longer required.
- `@hedgedoc/markdown-it-task-lists` was moved to `@hedgedoc/markdown-it-plugins` 
- deprecated repo - https://github.com/hedgedoc/markdown-it-better-task-lists 
- new new repo https://github.com/hedgedoc/markdown-it-plugins
> fix: remove deprecated `@types/mermaid` and `@hedgedoc/markdown-it-task-lists`

- packages/slidev/node/plugins/loaders.ts
Fixes https://github.com/slidevjs/slidev/issues/865
Remove import of `virtual:windi-devtools` causing pending call to `/@windicss-devtools-update` to hang indefinitely
> fix: timeout export with windicss

- packages/client/internals/Print.vue
Sometimes the pdf export print an additional blank page at the end.
> fix: blank page at the end

- packages/create-app/template/netlify.toml
Hello there 👋🏽 
I noticed when I was setting things up that because the `netlify.toml` file redirects _all_ traffic to `/index.html` it was blocking Netlify from completing the Let's Encrypt certificate verifcation process.
This PR adds an additional redirect to `netlify.toml` to resolve this which ensures that requests to the `.well-known` path continue as expected.
> fix: update Netlify configuration to allow for Let's Encrypt verifications

- packages/client/package.json
- packages/slidev/package.json
- pnpm-lock.yaml
I am writing a slide about TypeScript tricks, but the ts version in `monaco-editor@^0.33.0` is `4.5.5`(which is released almost 2 years ago), that lacks a lot of features.
And the latest `monaco-editor@^0.37.x` has ts `5.0.3` built-in.
> chore: update `monaco-editor`

- demo/starter/slides.md
- packages/client/builtin/TocList.vue
In Firefox the built-in `TOC` element gets rendered with implicit blocking `div` + `p` which results in follwing problem:
Chromium seems to think otherwise of those blocking elements. Nonetheless, resetting those element styles fixes the problem both for Firefox and Chromium browsers.
> fix: prevent ToC links to be blocking element

- packages/client/layouts/end.vue
Defaults to `END` if no slot is set (like before)
> feat: support slot for `end` layout

- packages/slidev/node/plugins/preset.ts
- packages/slidev/package.json
- pnpm-lock.yaml
This feature will allow theme authors to include public assets (e.g. images) that can be used in slides by users of that theme. Any files present in the `public` folder of a theme will be copied over to the `theme/` folder in the output directory when slides are being built.
These files can be referenced in slides using `/theme/path/to/asset.ext`. Example:
In the theme:
```
public/my-image.png
public/nested/another-image.png
```
will be available under
```
theme/my-image.png
theme/nested/another-image.png
```
I will open a PR for the documentation after/when this PR is accepted :)
> feat: include public assets from theme in build, fixes #727

- packages/client/iframes/monaco/index.ts
support tsx and jsx,and then add following code to `setup/monaco.ts`.
```ts
monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
noSemanticValidation: true,
noSyntaxValidation: true, // This line disables errors in jsx tags like <div>, etc.
});
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
jsx: monaco.languages.typescript.JsxEmit.React,
jsxFactory: 'React.createElement',
reactNamespace: 'React',
allowNonTsExtensions: true,
allowJs: true,
target: monaco.languages.typescript.ScriptTarget.Latest,
});
```
> feat(monaco): support tsx and jsx

- packages/slidev/node/plugins/monacoTransform.ts
- Fixes #959
When CJS build is bundled the compiler transforms dynamic `import()` into `require()`:
```diff
- const { resolvePackageData } = await import("vite");
+ const { resolvePackageData } = await Promise.resolve().then(() => require("vite"));
```
Vite's CJS build does not support the `resolvePackageData` and throws following error:
```
5:34:30 PM [vite] Internal server error: "resolvePackageData" is not supported in CJS build of Vite 4.
Please use ESM or dynamic imports `const { resolvePackageData } = await import('vite')`.
at module.exports.<computed> (/Users/x/project/node_modules/.pnpm/vite@4.3.3/node_modules/vite/index.cjs:30:11)
at getPackageData (/Users/x/project/node_modules/.pnpm/@slidev+cli@0.40.16_patch_hash=a53stzchrmu3p273saucptgjli_postcss@8.4.23_react-dom@16.14.0_react@ …
```
> fix: preserve dynamic import of vite

- packages/client/builtin/CodeBlockWrapper.vue
- packages/client/internals/PrintContainer.vue
- packages/client/internals/SlideContainer.vue
- packages/client/styles/code.css
- packages/slidev/node/plugins/markdown.ts
Code example:
https://gist.github.com/fr0zn/fe5292397f614b46bcbb5e6909bc9aad
Demo:
Reference: #310
> feat: support setting startLines for codeblocks (#310)

- packages/slidev/node/plugins/markdown-it-prism.ts
- packages/slidev/package.json
- pnpm-lock.yaml
- test/__snapshots__/markdown-it-prism.test.ts.snap
- test/markdown-it-prism.test.ts
The current implementation of line breaking of Prism-highlighted code is incorrect. It first splits code in separate lines and feed these to the highlight method. This does not work correctly for many kinds of code: JavaScript multiline strings and doc comments, XML attributes over multiple lines, etc.
As an alternative this PR sends the whole code to Prism and then splits line by line. A problem that then occurs: a newline can start when one or more tags are still open. In the PR I addressed this by parsing the HTML and closing/reopening tags for each line. I've searched the Prism API to see if there is some way around this, but haven't found it yet.
> fix: prism highlighted line breaking

- packages/client/layoutHelper.ts
- packages/client/layouts/image-left.vue
- packages/client/layouts/image-right.vue
- packages/client/layouts/image.vue
fixes https://github.com/slidevjs/slidev/issues/798
Continue of the previous [PR](https://github.com/slidevjs/slidev/pull/862), accidentally deleted branch while rebasing.
With this additional prop to image layouts (image, image-left, image-right), we can now able give custom css [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size). The default will remain `cover` 
My main motivation was to be able to use `contain`. Because I wasn't able to fit vertical photographs, let's cover all the different needs.  
Example usages:
```
---
layout: image
image: https://iili.io/HzdAhJV.png
backgroundSize: contain
---
```
```
---
layout: image-left
image: https://iili.io/HzdAhJV.png
backgroundSize: 20em 70%
---
```
On this PR, I also excluded 
- image-custom layout [from …
> feat: custom `backgroundSize` for image layouts (#798)

- packages/create-app/index.js
> fix: get `pkgManager` compatible edge case

- packages/slidev/node/plugins/loaders.ts
- packages/slidev/package.json
- pnpm-lock.yaml
closes #1092
Initially support Vue HMR of the latest `@vitejs/plugin-vue`. Removed hacked internal `handleHotUpdate` that from `@vitejs/plugin-vue` for avoiding breaking changes in the future.
For support finer-grained update, now needs to be handled HMR logic, comparing which part `script` or `template` is changed, by slidev itself.
> fix: vue hmr

- packages/client/composables/useViewTransition.ts
- packages/client/internals/SlidesShow.vue
**Details:** 
- https://github.com/slidevjs/slidev/issues/1100
**Defects:**
At least on Windows, the text is slightly offset during animation, which seems to be related to the margin CSS.
I'm not sure if there's a better way to introduce a view transition feature, at least the current code works for my needs.
> feat: view transition support

- demo/starter/slides.md
- packages/client/builtin/CodeBlockWrapper.vue
- packages/client/builtin/KaTexBlockWrapper.vue
- packages/client/logic/utils.ts
- packages/client/styles/katex.css
- packages/slidev/node/plugins/loaders.ts
- packages/slidev/node/plugins/markdown.ts
Reslove #266 
Base syntax is as same as [code blocks line highlighting](https://sli.dev/guide/syntax.html#line-highlighting)
Example:
```latex
$$ {2-3|all}
\begin{array}{c}
\nabla \cdot \vec{\mathbf{B}} & = 0
\end{array}
$$
```
> feat: support katex line highlighting

- packages/client/logic/nav.ts
@pposca raised a bug on hideInToc flag used on the Toc component which makes the hideInToc flag ineffective in latest versions. (https://github.com/slidevjs/slidev/issues/1109)
I observed the same bug and tries to propose a fix to the issue.
Context:
- The bug has been added between version `0.43.0-beta.5` and version `0.43.0-beta.6`. 
- Responsible commit is https://github.com/slidevjs/slidev/commit/16c41ce51fe094ccc7e03dccd6ba0faf5c7acacc
- Changed code is on line `571-572`
- Impacted code creating the bug is in `packages/client/logic/nav.ts` line `198`
Fix:
I propose a fix which uses what seems to be a more safe and stable way of accessing `hideInToc`. I don't have great experience on the architecture of the application so I let it at the maintainer's appreciation to validate the …
> fix: hideInToc bug

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
Hello,
To improve the usability and use cases provided by the table of content component (`ToC`), I propose to add two new functionalities which are as follow:
- An offset applied to the highest level of the ToC. It allows to create presentation which does not start at the 1st 'chapter'. This is useful for example when you want to create a long presentation with multiple chapter but split in multiple documents. Function is implemented by adding a `start` attribute to the `ToC` component. The given number corresponds to the offset as used with the HTML `ol` element.
- Add the possibility to customize the style of the ordered list used in the ToC. Function is implemented by adding a `listStyle` attribute to the ToC component. It takes a string or a list of string (ex: …
> feat: add start offset and customization option to ToC list

- packages/client/composables/useNav.ts
- packages/client/modules/context.ts
> fix: export `go` function on `nav` object

- packages/client/layouts/iframe-left.vue
This broke in 1d4e2d1 and resulted in the righthand-side content being placed outside of the slide.
> fix(layouts): show righthand-side of iframe-left

- README.md
- demo/composable-vue/components/VueUse.vue
- demo/composable-vue/slides.md
- demo/starter/slides.md
- packages/client/builtin/PlantUml.vue
- packages/client/internals/DrawingControls.vue
- packages/client/internals/Editor.vue
- packages/client/internals/HiddenText.vue
- packages/client/internals/InfoDialog.vue
- packages/client/internals/NavControls.vue
- packages/client/internals/NotesView.vue
- packages/client/internals/Presenter.vue
- packages/client/internals/RecordingControls.vue
- packages/client/internals/SlidesOverview.vue
- packages/create-theme/template/example.md
- packages/slidev/template.md
- pnpm-lock.yaml
- provide `alt` attributes for `<image>` elements. Use`alt=""` for decorative images
- add `HiddenText` component for icon button usage. The component uses the WindiCSS class `src-only` to correctly hide elements visually but read texts out for screen readers
closes #1142
> fix(a11y): add missing alternative texts

- packages/client/internals/PrintSlideClick.vue
Slides with animations (e.g., code highlight clicks, or custom (non v-click) clicks) were exported in their initial state instead of their final state.
The cause was the /print view that was always passing `:clicksDisabled="false"` even for full slide export.
When clicks are disabled, the print view now uses the same delegation as the Overview https://github.com/slidevjs/slidev/blob/ce8c338e9d15d9e818c11f5badb2ff2afe10c19b/packages/client/internals/SlidesOverview.vue#L133-L140
> fix: code animation pdf exports the first step instead of last

- packages/slidev/node/plugins/monacoTransform.ts
- packages/slidev/package.json
- pnpm-lock.yaml
https://github.com/vitejs/vite/pull/14584 is removing the API for future perf optimizations and bug fixes. Since the API is not widely used, I've made a PR to refactor it away directly.
This uses [`vitefu`](https://github.com/svitejs/vitefu) which I maintain on the side and implements the same heuristic, and is also used by frameworks like Svelte, Solid, and Astro today.
(I've not tested this particular code, but I hope the CI covers it)
> refactor: remove using resolvePackageData from Vite

- packages/types/package.json
This should allow the `@slidev/types` exports to properly resolve.
I wasn't able to test locally, but I believe this should resolve #1167
> fix: type exports

- packages/client/routes.ts
- packages/slidev/node/plugins/loaders.ts
This Pr fix the issue #1164.
from v0.43.0 the frontmatter is not merged in route.meta in slidev/node/plugin/loaders.js , but some fields are injected as computed property.
As a result the "preload" field is not anymore injected in route.meta and not found in :
https://github.com/slidevjs/slidev/blob/main/packages/client/internals/SlidesShow.vue#L21-L26
This Pr add preload in RouteMeta as other existing property (clicks, ...).
> fix: 'preload: false' in frontmatter not working, fix #1164

- packages/client/internals/PrintSlide.vue
[custom clicks count](https://sli.dev/guide/animations.html#custom-clicks-count) was not applied for `slidev export --with-clicks`.
fixes #1168
> fix(export): use custom clicks count

- packages/client/composables/useViewTransition.ts
Setting transitions on a slide applies to the transition between that slide and the next slide.
For example, in the following example,
```
foo
---
transition: slide-left
---
bar
---
baz
```
`transition: slide-left` will apply to `bar -> baz`/`bar <- baz`, but not to `foo -> bar`/`bar <- foo`.
`transition: view-transition` was not working like that. It was applied to both of them. This PR fixes that.
> fix: don't apply view-transition between previous slide

- packages/client/layouts/two-cols-header.vue
Restores the `bottom` slot from [the original feature PR](https://github.com/slidevjs/slidev/pull/1114) by fixing the grid layout.
> fix(layout): two-cols-header grid with bottom

- cypress/e2e/examples/basic.spec.ts
- cypress/fixtures/basic/components/DecorateWithLi.vue
- cypress/fixtures/basic/components/WrapInClicks.vue
- cypress/fixtures/basic/components/WrapInClicksDecorate.vue
- cypress/fixtures/basic/components/WrapInComponentInClicks.vue
- cypress/fixtures/basic/slides.md
- packages/client/builtin/VClicks.ts
fixes https://github.com/slidevjs/slidev/issues/1190
This is a fix for the issue, i.e. it makes it possible to have a component defined somewhat like this:
```html
<template>
<v-clicks><slot></v-clicks>
</template>
```
NB: slots are detected using typeof i.type === 'symbol', I'm not sure if there is a more robust way (like importing the symbol from vue implementation?)
NB: another case, that is more difficult to handle is the one where we have a component that renders e.g. as an `ul` and that is used in a nested list, this is currently (still) missed by v-clicks as its logic works on the un-rendered component.
> fix: handle slot in v-clicks

- packages/client/builtin/VClicks.ts
Implemented VClicks feature for table tags in response to the request in issue #1102. 
Now, each row in a table shows up upon each click.
```markdown
<v-clicks>
|                  | emacs | vim            |
| ---------------- | ----- | -------------- |
| startup          | slow  | fast           |
| difficult to use | yes   | yes            |
| keybinds used on | Mac   | Linux-Commands |
| GUI              | yes   | no             |
</v-clicks>
```
https://github.com/slidevjs/slidev/assets/19663115/afc70227-ae39-4019-ae6a-6649e5b88fa4
> feat: table support for v-clicks

- packages/slidev/node/plugins/markdown.ts
- test/__snapshots__/transform.test.ts.snap
- test/transform.test.ts
Closes #1208.
Switched `\w` to `\S` in the regexp for matching the `::slot-name::` syntax.
`\S` matches any non white-space character, not sure if it is the right group or if we need some other custom matching list.
I am not familiar enough with Vue to know which characters are allowed for slot names.
> fix: allow more characters for slot names

- packages/slidev/node/build.ts
- packages/slidev/node/common.ts
- packages/slidev/node/server.ts
Closes #1040.
- `mergeViteConfigs` now also loads the local `vite.config.ts` file and merges the `slidev` options from it.
(I first tried merging everything from the local config, but it contains loads of default vite plugins and made the pipeline crash.)
- In the `build` and `createServer` functions, we first create a merged viteConfig object without `ViteSlidevPlugin`.
We then create the plugin, using `viteConfig.slidev` as the `pluginOptions` argument, effectively allowing themes and addons to override the options.
Finally, we add the plugin to the `viteConfig`.
I did not add any tests for this feature.
Is this necessary and if so, from which test can I start as a reference ?
> feat: ViteSlidevPlugin `pluginOptions` argument now can be modified by themes and addons

- packages/client/builtin/KaTexBlockWrapper.vue
Consider the following `slides.md` file
```
---
layout: default
---
$$ {1|2|3|4}
\begin{align*}
R=& (111....)_2 + (111....)_2 \\
=& \sum_{n=0}^{n-1} 2^n + \sum_{n=0}^{n-1} 2^n \\
=& \: 2*{\sum_{n=0}^{n-1} 2^n} \\
=& \: 2*(2^{n} - 1)
\end{align*}
$$
```
I would expect the [highlighting to work for LaTeX ](https://sli.dev/guide/syntax.html#latex-line-highlighting).
However it doesn't.
This generalizes the logic of finding the individual rows by iterating over all .col-align-XXX classes that contain the individual equation rows.
> fix: Highlighting latex equations when using \begin{align*}

- packages/client/builtin/KaTexBlockWrapper.vue
- packages/slidev/node/plugins/markdown.ts
Code blocks support providing an "at:0" to start at the nth click.
Latex blocks didn't support this feature... until now :).
This PR allows using the {at:0} syntax for latex blocks to synchronize clicks
> feat: Support highlight start at for latex

- packages/client/builtin/KaTexBlockWrapper.vue
PR: https://github.com/slidevjs/slidev/pull/1228
Introduced a regression in which vector symbols get classified as a latex line, causing the line highlighting to break.
By adding [:scope](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) to the css selector only the direct descendants on the parent will be selected, thereby skipping child elements (vectors) that have the same css structure
```
---
layout: default
---
$$ {0|1|2|3|all}
\begin{array}{c}
\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &
= \frac{4\pi}{c}\vec{\mathbf{j}} \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}}\\
\nabla \cdot \vec{\mathbf{B}} & = 0 
\end{array}
$$ …
```
> fix: Latex line highlighting for vector equations

- packages/client/App.vue
- packages/client/package.json
- packages/client/setup/main.ts
- pnpm-lock.yaml
This PR removes the built-in [vue-starport](https://github.com/antfu/vue-starport) support, as the [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) should cover it in a much better way.
> refactor!: remove build-in vue-starport support

- packages/parser/src/core.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
This PR adds the `SlideInfoBase.frontmatterRaw` field, which is used to preserve comments in frontmatter for the Prettier plugin for Slidev. (See https://github.com/slidevjs/slidev/issues/1261#issuecomment-1920629676)
```diff
export interface SlideInfoBase {
raw: string
content: string
note?: string
frontmatter: Record<string, any>
+  frontmatterRaw?: string
frontmatterStyle?: FrontmatterStyle
title?: string
level?: number
}
```
`frontmatterRaw` stores only the YAML part of frontmatter.
> feat: add `SlideInfoBase.frontmatterRaw`

- packages/client/builtin/Tweet.vue
This PR:
- adds a `cards` prop to the `<Tweet />` component which corresponds to the [`cards` parameter of the 'Embedded Tweet' API](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference)
Setting `cards` to `"hidden"` makes it so link previews do not appear, which is pretty useful in presentations considering they add a ton of vertical space to the 'embed'
---
*I can make a pr updating the docs site as well if this goes through*
> feat: add "cards" option to 'Tweet' component

- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
- packages/types/src/cli.ts
This PR adds a new command line argument `--scale`:
```sh
slidev export --format png --scale 100
slidev export --format png --scale 0.1 --per-slide
slidev export --format md --scale 100
```
The internal of this feature is:
```ts
const context = await browser.newContext({
// ...
deviceScaleFactor: scale,
})
```
This can be a way to control the quality of the png export. (#1263)
| 0.1x | ![0.1x](https://github.com/slidevjs/slidev/assets/63178754/d2683fb6-8b74-4d6c-906b-d95c328012c6) |
| --- | --- |
| 2x | ![2x](https://github.com/slidevjs/slidev/assets/63178754/748dfb11-40bc-4d42-a4f8-8c634e4c7c1c) |
> feat: add `scale` arg for image export (#1263)

- packages/client/setup/codemirror.ts
- packages/slidev/node/plugins/extendConfig.ts
fix #1281
This PR fixes #1281 by partly reverts 4ef7fc934586758d2c8bdaa8bb0afa6e4605fad2.
It is confusing that the `codemirror` package isn't explicitly excluded from `optimizeDeps`, but it is in fact not optimized (**only when `@slidev/cli` and `@slidev/client` are installed from npm registry. In this monorepo, it is OK**). And `codemirror@5` is a UMD package, but it is then wrongly imported as an ESM package, which causes the issue. This PR re-adds `codemirror` related packages to `optimizeDeps.include` array, and import `CodeMirror` as default import.
I am not sure whether other packages removed from the `include` list by 4ef7fc934586758d2c8bdaa8bb0afa6e4605fad2 (listed below) should be added again or not.
**Lines removed in 4ef7fc934586758d2c8bdaa8bb0afa6e4605fad2**:
```ts
import { …
```
> fix: `codemirror` import error (#1281)

- packages/client/builtin/VClick.ts
fix #1214
This PR wraps `VClick`'s **top-level** text node child into a `span`, or other element specified by the `wrapText` prop.
Now, the following click animations work properly.
```markdown
<v-click> 123 </v-click>
<v-click :wrap-text="v=>h('div', v)">
0 <del>2</del>
</v-click>
abcd <v-click>_d_ ef</v-click> ghi <v-click>j**kl**</v-click>
```
> feat: allow `Text` as `VClick`'s top-level child (#1214)

- packages/client/logic/note.ts
- packages/slidev/node/plugins/loaders.ts
In this PR, slide note editing is handled separately.
- When appending or prepending newlines and whitespaces in the note editor in Presenter mode, the note written to the disk is trimmed, but in the editor the whitespaces are reserved.
- Avoid unnecessary HMRs.
- fix #1157
> fix: slide note sync (#1157)

- packages/client/builtin/Mermaid.vue
fix #1074
This PR adds the display of Mermaid rendering error.
> feat: display error message from Mermaid

- packages/client/setup/codemirror.ts
I found `codemirror` import broken again because of the updates of dependencies after #1283 was merged. This PR fixes this.
> fix: `codemirror` import error, again

- .github/workflows/autofix.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Resolve deprecation warnings in workflows, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore(gha): Update actions/checkout and actions/setup-node

- packages/parser/src/fs.ts
- packages/slidev/node/plugins/loaders.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
fix #1111
Previously, editing subslides in the CodeMirror editor will delete all the other slides in the imported markdown file. This PR fixes this.
> fix: save external slide (#1111)

- packages/client/internals/InfoDialog.vue
- packages/client/internals/Modal.vue
- packages/client/internals/SlidesOverview.vue
This PR fixes three warnings about `update:modelValue` is not defined in `defineEmits`.
> fix: `defineEmits` caused warnings

- packages/client/internals/Editor.vue
- packages/client/internals/NoteEditor.vue
- packages/client/logic/note.ts
- packages/parser/src/core.ts
- packages/parser/src/fs.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
- packages/slidev/node/plugins/loaders.ts
- packages/slidev/node/plugins/transformSnippet.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
- test/parser.test.ts
- test/transform.test.ts
This PR refactors the data structures for parsed and loaded data.
- Every markdown source file is represented by a `SlidevMarkdown` object, including the entry markdown file:
```ts
export interface SlidevMarkdown {
filepath: string
raw: string
slides: SourceSlideInfo[]  // all the slides in this Markdown file
}
```
- The previous `SlidevMarkdown` is renamed to `SlidevData`:
```ts
export interface SlidevData {
slides: SlideInfo[]  // the actually displayed slides (disabled slides excluded)
entry: SlidevMarkdown
config: SlidevConfig
headmatter: Record<string, unknown>
features: SlidevFeatureFlags
themeMeta?: SlidevThemeMeta
markdownFiles: Record<string, SlidevMarkdown>
watchFiles: string[]
}
```
There should be only one `SlidevData`, and at least one `SlidevMarkdown`.
- Fixes (unreported) …
> fix: nested multiple-entry slides

- packages/slidev/node/cli.ts
resolves #1180.
This PR adds a `--bind` CLI option to bind a specific address in remote mode.
The reason why this option isn't named as `--host` is that,  `--host` without a string arg in Vite works like `--remote` in Slidev. If this option is named `--host`, it will make the user confused.
> feat: add `--bind` option

- packages/client/constants.ts
- packages/slidev/node/plugins/loaders.ts
fixes #1303.
This PR added a filter to remove unwanted fields from frontmatter to pass to the layout component. And pass the full frontmatter as `frontmatter` prop. (https://github.com/slidevjs/slidev/issues/1303#issuecomment-1952309397).
Current behavior on the first slide of the demo:
Not the best, but much better than before.
> fix: filter frontmatter (#1303)

- packages/parser/src/fs.ts
Previously, the `hide` option in frontmatter doesn't work, which violates the docs.
> fix: `hide` option in frontmatter

- packages/client/logic/nav.ts
- packages/client/routes.ts
- packages/parser/src/fs.ts
- packages/slidev/node/plugins/loaders.ts
This PR fixes the route meta of slides. So that the open-in-editor function is fixed and the total size of data is reduced.
> fix: slide route meta

- packages/client/builtin/VClicks.ts
fixes #1320
Partially reverts aa0cab441fe068419bb34ab75a29453d584a7c33.
#1320 is caused by that one same `li` in `<v-clicks>` is applyed two `v-click` directives. Once in the main view, and once in the slides overview.
> fix: `VClicks` component

- packages/slidev/node/plugins/markdown.ts
fixes #1316.
Previously, only "full" mustache syntax (`{{...}}`) is escaped. However, Vue regards `{{` as the start of mustache syntax, no matter what the following code is.
This PR escapes all `{{` in Shiki-rendered HTML. I think it is only 99.999% safe, but I can't find a better solution.
In Vitepress, only `{{...}}` is replaced:
https://github.com/vuejs/vitepress/blob/28989df83446923a9e7c8ada345b0778119ed66f/src/node/markdown/plugins/highlight.ts#L127-L134
> fix: escape `{{` in code (#1316)

- packages/client/builtin/Tweet.vue
- packages/client/composables/tweet.ts
- packages/client/composables/useTweetScript.ts
Fixes #1309.
This PR fixes **Firefox-only** issue about multiple `Tweet` components. The cause is very similar to https://github.com/vueuse/vueuse/issues/2027.
This PR wraps `useScriptTag` by `createSharedComposable`. I've tested multiple Tweet components in Firefox119 in Browserling and found this fix works well.
> fix: multiple Tweet component (#1309)

- packages/client/constants.ts
- packages/client/internals/SlideWrapper.ts
This PR adds a `zoom` option in **every page**'s frontmatter to scale each slide **separately**.
| `zoom: 0.3` | `zoom: 1` (default) | `zoom: 3` |
| - | - | - |
| <img width="1280" alt="image" src="https://github.com/slidevjs/slidev/assets/63178754/ab6145d0-e71f-44ed-832b-f8b98d43ed18"> | <img width="1280" alt="image" src="https://github.com/slidevjs/slidev/assets/63178754/6bada295-d4ef-4806-b36b-614b76ea7f52"> | <img width="1280" alt="image" src="https://github.com/slidevjs/slidev/assets/63178754/37e44a10-2d62-4b08-b509-98ccea86e7d4"> |
Resolves #1075.
If we want to zoom all the slides, we can use the `canvasWidth` option in the headmatter, which has almost the same effect as applying this `zoom` option to all slides.
> feat: add `zoom` option in page frontmatter

- packages/client/logic/note.ts
- packages/slidev/node/plugins/loaders.ts
- packages/types/src/types.ts
This PR adds a new type:
```ts
/**
* Editable fields for a slide
*/
export type SlidePatch = Partial<Pick<SlideInfoBase, 'content' | 'note'>>
```
And fixes slide patching, e.g. editing notes.
> fix: slide patching

- packages/client/internals/Editor.vue
Reset the history of editors when route (i.e. slide) changes. Thus too many `ctrl+z`s will not set the content of the slide to the previous slide.
> fix: reset CodeMirror history when route changes

- demo/starter/slides.md
- packages/client/main.ts
- packages/client/modules/context.ts
- packages/client/modules/v-click.ts
- packages/client/modules/v-mark.ts
- packages/client/package.json
- packages/client/styles/index.css
- packages/slidev/node/cli.ts
- pnpm-lock.yaml
I probably need to write the docs after my conf, but here is a general idea:
This pr introduces a `v-mark` directive that can trigger [Rough Notation](https://github.com/linkstrifer/react-rough-notation) around that target element.
`v-mark.underline` for Unerline mark, `v-mark.circle` for Circle mark, etc. Default to `underline`
`v-mark.red` make the notation `red`. Supported builtin color themes from UnoCSS. For custom colors, use object syntax `v-mark="{ color: '#234' }"`
`v-mark` works like `v-click` and will trigger after a click. Same as `v-click`, it allows you to pass a custom click value, like `v-mark="5"` or `v-mark="'+1'"`.
When options object is provided, use as the `at` property: `v-mark="{ at: 5, color: '#234' }"
Refer to …
> feat: support `v-mark` powered by Rough Notation

- demo/starter/slides.md
- packages/client/builtin/VClick.ts
- packages/client/composables/useClicks.ts
- packages/client/constants.ts
- packages/client/internals/NoteDisplay.vue
- packages/client/internals/NoteEditor.vue
- packages/client/internals/NoteStatic.vue
- packages/client/internals/OverviewClicksSlider.vue
- packages/client/internals/SlidesOverview.vue
- packages/client/logic/nav.ts
- packages/client/pages/overview.vue
- packages/client/pages/presenter.vue
- packages/client/styles/index.css
- packages/slidev/node/plugins/loaders.ts
resolve #1333
This PR introduces a special marker `[click]` in slide notes, used to separate chunks in the node and highlight the active chunk as the slide progresses. This is useful for better segmenting of long transcripts. 
Preview: 
https://github.com/slidevjs/slidev/assets/11247099/2fbf3928-dd6f-4aca-b4f5-7085f50d0e7f
> feat: support clicks in notes

- packages/parser/src/fs.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
- packages/types/src/types.ts
While trying to make a preparser dependent on whether we are exporting slides or not, one user tried to naturally import nav as in:
```ts
import { definePreparserSetup } from "@slidev/types";
import { isPrintMode } from "@slidev/client/logic/nav.ts";
function removeSlidesWithHidePrint(lines) {...}
export default definePreparserSetup(() => {
return [
{
transformRawLines(lines) {
if (isPrintMode) {
removeSlidesWithHidePrint(lines);
}
},
},
];
});
```
But `nav` includes `routes` which includes some `Play.vue` file which gives an error.
My understanding is that the reason is the following: the parsing code is not running in the client side, so most of these (routes, vue loader, etc) are not (supposed to be) available.
This PR passes the running "mode" (dev|build|export) to the preparser.
NB: …
> feat: allow preparsers to access the run mode (dev,export,build)

- packages/client/internals/PrintContainer.vue
fix https://github.com/slidevjs/slidev/issues/1207
https://github.com/slidevjs/slidev/issues/1207 is caused by [_stacking context_](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context#description)
> fix: black background when exporting to PDF

- packages/client/builtin/KaTexBlockWrapper.vue
- packages/slidev/node/plugins/markdown.ts
This PR applies the same changes as 8f45fa838bfbcafbf15a54299451d8beb72ddb28 to Katex blocks.
> fix: Katex block clicks animation

- demo/starter/package.json
- demo/starter/slides.md
- pnpm-lock.yaml
This PR removes the usage of `monacoTypesAdditionalPackages` in the demo slide.
Because `@slidev/type` is not a dependency of the `create-app` template, but is used in the demo, which will cause an error.
If we add `@slidev/type` as a dependency of the template, users may think it is a must to install this package.
> fix: remove `monacoTypesAdditionalPackages` from demo

- packages/slidev/node/plugins/extendConfig.ts
This PR adds missing deps to the `INCLUDE` list.
It is OK to merge this now, but it might be safer to merge this after the user-side CI is done.
> fix: add missing CodeMirror deps to include list

- packages/client/composables/useClicks.ts
- packages/client/internals/ClicksSlider.vue
Previously, when double-clicking the bar, the URL will become something like `http://localhost:3031/presenter/5?clicks=99999`.
So <kbd>Left</kbd> can only minus the `clicks` num by one, and actually has no effect. Because the new clicks num may be `99998`, which is still a very large num.
This PR sets `clicks` to `total` when double-clicking the clicks bar, and prevents setting `usePrimaryClicks().click` to be greater than `total`.
This PR also prevents the slider to be focused. Otherwise, the <kbd>Right</kbd> will try to add the range input's value, instead of going to the next slide.
> fix: double click operation in clicks slider

- packages/client/builtin/ShikiMagicMove.vue
Previously, there was a white scroll bar shown when magic moving, and hidden when animation finished. This PR hides this white scroll bar.
> fix: hide scroll bar in Shiki magic move

- packages/client/builtin/Toc.vue
- packages/client/composables/useContext.ts
- packages/client/composables/useNav.ts
- packages/client/composables/useSwipeControls.ts
- packages/client/composables/useTocTree.ts
- packages/client/internals/NavControls.vue
- packages/client/internals/PrintContainer.vue
- packages/client/internals/PrintSlideClick.vue
- packages/client/internals/SlidesShow.vue
- packages/client/logic/nav-state.ts
- packages/client/logic/nav.ts
- packages/client/logic/slides.ts
- packages/client/logic/transition.ts
- packages/client/modules/context.ts
- packages/client/pages/play.vue
- packages/client/pages/presenter.vue
- packages/client/setup/root.ts
- packages/client/setup/shortcuts.ts
- packages/client/utils.ts
- shim.d.ts
Move most of the logics out of `logic/nav.ts` with became a bit bloated overtime. This would help better maintainability in the long term
This can be a breaking change if you are relying on the exported props from `nav.ts` - basically renaming things, please refer to the types to migrate
> refactor!: separating nav.ts for better scoping

- .github/workflows/smoke.yml
Previously, the smoke test CI would fail when the current version hasn't been published yet.
> ci: fix production smoke test

- packages/client/context.ts
- packages/client/shim-vue.d.ts
For some unknown reason, **some** imports inside the `declare module` block are neither an error nor have any effect.
(As mentioned in https://discord.com/channels/851817370623410197/855378319515582474/1214524756217434166)
This PR fixes this by using dynamic imports instead.
This PR also completes `ComponentCustomProperties`.
However, though `shim-vue.d.ts` looks OK now, I am still wondering how this file takes effect on the user side -- there seems to be nowhere importing this file.
> fix: types in shim files

- packages/client/index.html
- packages/client/internals/SlideLoading.vue
- packages/client/modules/mermaid.ts
- packages/slidev/node/export.ts
This PR fixes:
- Wait for slides to be all loaded before printing to PDF.
- Wait for mermaid charts to be all loaded
- Hide Monaco's aria container to avoid the empty page at the end of the PDF.
> fix: slide exporter

- packages/client/logic/utils.ts
in the Mermaid render, we use `makeId` to generate the DOM element's id, which cannot start with numbers. As a simpler fix, this PR removes numbers in id.
> fix: id should not contain numbers

- packages/slidev/node/plugins/loaders.ts
This bug will silently change the config, which will make the page reload instead of HMR in the very first edit.
> fix: monaco types loader

- packages/slidev/node/plugins/markdown.ts
- test/transform-magic-move.test.ts
the code languages 'angular-ts' and 'angular-html' are currently excluded from magic move as the code regexp doesn't handle the "-". This should fix it, also wrote a test for it. Let me know if any adjustments are needed.
> fix: allow hyphenated languages for magic move, e.g. angular-ts

- docs/guide/animations.md
It seems that `<div> a **b** </div>` doesn't have the bold font now. (If I remember correctly, it had bold font at that time)
> docs: fix `v-click` example

- docs/custom/config-code-runners.md
- packages/types/src/code-runner.ts
Because `Runner Context` is shorter and easy to miss, I inlined the type definition. Otherwise, the user may not know what the context can do.
> docs: update code runner docs

- packages/client/internals/SideEditor.vue
When the size of CodeMirror editor changes, we have to call `editor.refresh()` manually. (CodeMirror itself only listens to window size changes).
> fix: refresh CodeMirror editror when size changed

- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
- packages/slidev/node/resolver.ts
- packages/types/src/options.ts
- packages/types/src/vite.ts
- test/utils.test.ts
Close #1401
This PR resolves `userRoot` to `dirname(entry)`
> fix: user root resolver

- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
resolve #1412.
Allow `theme` to be `null`. `theme: null` is now equivalent to `theme: none`, while `theme: undefined` is still resolved as `theme: undefined`
> feat: allow `theme` to be `null`

- cypress/e2e/examples/basic.spec.ts
- packages/client/composables/useNav.ts
- packages/client/composables/useViewTransition.ts
- packages/client/logic/route.ts
- packages/client/logic/transition.ts
fix #1408
This PR fixes routing and view transition.
Previously, a navigation operation would make more than one route changes, which overrides themselves, resulting in #1408.
And when navigating from a non-view-transition (i.e. `TransitionGroup`) slide to a view-transition slide, we need to first wait for `TransitionGroup` element to become a normal `div` element. Otherwise when the route changes, view-transition will not play because it was still a `TransitionGroup` element. Currently a `setTimeout(50)` is added (`nextTick` not working for some unknown reason), but the root fix will be adding an `enabled` prop to `TransitionGroup` by Vue (I will open an issue in Vue for this later).
However, before and in this PR, if you switch slides very quickly, the displayed slide will mismatch the …
> fix: routing and view transition

- packages/client/composables/useClicks.ts
- packages/client/internals/PrintSlide.vue
- packages/client/modules/v-mark.ts
fix #1416. close #1418.
This PR:
- Fix print without per clicks (#1416)
- Show rough notation in print mode
Previously rough notation is not shown in print mode because click animation is disabled. In this PR the rough notation will always be shown when the click animation is not working, aligning with the behavior of `v-click`.
> fix: print mode

- packages/slidev/node/integrations/addons.ts
> fix: error when no `engines` field in package.json

- docs/builtin/components.md
- packages/client/builtin/RenderWhen.vue
resolve #1427.
- Add `print` context
- Add `#else` slot, which will be rendered if the context does not match.
> feat: enhance `RenderWhen` component

- packages/client/builtin/CodeBlockWrapper.vue
- packages/client/builtin/KaTexBlockWrapper.vue
- packages/client/builtin/ShikiMagicMove.vue
- packages/client/builtin/SlidevVideo.vue
- packages/client/builtin/VClickGap.vue
- packages/client/composables/useClicks.ts
- packages/client/composables/useNav.ts
- packages/client/internals/PrintSlide.vue
- packages/client/internals/QuickOverview.vue
- packages/client/modules/v-click.ts
- packages/client/pages/overview.vue
- packages/types/src/types.ts
This PR removes `clickContext.disabled`, which was previously used in print mode. So when exporting without clicks, the last click will always be printed. Previously, all animations were just removed, which works almost the same as this PR, but this PR could be more intuitive.
> fix: remove `clickContext.disabled`

- netlify.toml
- package.json
- packages/slidev/node/cli.ts
- scripts/demo.mjs
The demo was no longer included in the doc site since https://github.com/slidevjs/slidev/commit/4f5bb6820d47e6eaba8836a8a933ec29a8b3112e
check this out: https://sli.dev/demo/starter/7
And I've added [`PLAYWRIGHT_BROWSERS_PATH=0`](https://playwright.dev/docs/browsers#hermetic-install) env virable on netlify settings to prevent `chromium executable doesn"t exist` error in a cached build. Just mentioning, not sure this project did this before.
> docs: build demo

- packages/create-app/template/_gitignore
- packages/create-theme/template/_gitignore
This PR updates the `.gitignore` file in the templates.
- Removed `index.html`, because users may have something to insert into `<head>` or `<body>` by providing an `index.html`.
- Add `.vite-inspect`. Sometimes `--inspect` option will generate this.
> fix: `.gitignore` template

- docs/guide/syntax.md
I found this link is error, and I fixed it.
> docs: link correction in guide syntax

- packages/client/builtin/ShikiMagicMove.vue
- packages/client/constants.ts
- packages/client/context.ts
- packages/client/internals/SlideWrapper.vue
Related chat: https://discord.com/channels/851817370623410197/851817371324645421/1220104499943837778
This PR adds a new `injectionSlideZoom` injection key, which represents `slideRoute.meta?.slide?.frontmatter.zoom ?? 1`.
> fix: Shiki magic move with `zoom` option

- packages/client/internals/SlidesShow.vue
> fix: style of `#twoslash-container`

- packages/client/internals/SlidesShow.vue
> fix: warning about `TransitionGroup`'s children must be keyed

- packages/slidev/node/vite/extendConfig.ts
fix #1437.
resolve #1410.
Currently, Slidev uses the dev version of Vue both in dev and build mode for a very long time. This PR uses the bundler version of vue instead.
> fix: use bundler version of vue

- docs/builtin/components.md
It wasn't obvious to me what each `RenderWhen`'s context targeted. I took the liberty to update the code based on what I understood of the source code.
> docs: flesh out RenderWhen's contexts

- packages/client/internals/PresenterMouse.vue
The cursor being a solid fill color doesn't show up well against a dark background in light mode (when the cursor is black) or a light background in dark mode (when the cursor is white).
This adds a contrasting stroke emulating a native cursor look.
Fixes #1477.
> fix: increase contrast for presenter cursor

- packages/client/setup/code-runners.ts
When doing an import, the typescript compiler automatically decides ["well this file must be a module".](https://stackoverflow.com/questions/65553572/typescript-adds-plain-export-statement)
https://github.com/slidevjs/slidev/blob/f04f2ebb4783f8bd5df70bf82aaaa9343c87215d/packages/client/setup/code-runners.ts#L158-L163
`import type {UnionToIntersection} from 'type-fest'` -> `export {};` 
However, since the compiled TS code getts embedded in a function, the empty export code doesn't fit into the body of a function.
https://github.com/slidevjs/slidev/blob/f04f2ebb4783f8bd5df70bf82aaaa9343c87215d/packages/client/setup/code-runners.ts#L73-L76
Instead you get  `ERROR: SyntaxError: Unexpected token 'export'`
See https://stackblitz.com/edit/github-qj6z8s?file=slides.md
This PR sanitizes the JS …
> fix: remove empty export from transpiled ts file

- docs/guide/exporting.md
- packages/slidev/node/cli.ts
- packages/slidev/node/commands/export.ts
- packages/types/src/cli.ts
Related to #1141.
It is hard to make sure every component is rendered completely before exporting. This option adds extra time before exporting.
> feat: add `--wait` option when exporting

- docs/builtin/components.md
- docs/custom/index.md
- packages/client/internals/Goto.vue
- packages/slidev/node/virtual/titles.ts
This PR contains:
- feat: `TitleRenderer` defaults to render current slide's title. So `no` becomes optional.
- Rename all usage of `Titles` component to `TitleRenderer`
> feat: `TitleRenderer` defaults to render current slide's title

- docs/custom/vue-context.md
- docs/guide/syntax.md
Clarifies note about static asset paths, to prevent others from making the same error I did in #1488. (This also includes the changes I suggested in #1484 / #1483 - not sure if this is ok)
> docs: clarify leading slash in `syntax.md`

- packages/client/internals/SlidesShow.vue
Hi, thanks a lot for this project! Slidev's my go-to tooling these days. Big fan of the project!
This PR:
- Allow overflow to be visible to enable negative margins for styling
I like to style my slides with negative margins (especially when using `two-cols`, etc.) but with the change introduced in https://github.com/slidevjs/slidev/commit/c820e23b10581191a42bbf51c04bfd2caa49077a, it was hard to customize it to my liking.
Not sure there are any other side effects to this change, but it took me some time to fix it so I figured I'd open a PR :)
My current workaround was to include in `styles/main.css`:
```css
.slidev-page {
/* https://github.com/slidevjs/slidev/commit/c820e23b10581191a42bbf51c04bfd2caa49077a */
overflow: visible !important;
}
```
> fix: revert `overflow-hidden` for `SlideWrapper`

- demo/starter/slides.md
- packages/client/setup/code-runners.ts
- packages/slidev/node/vite/loaders.ts
- packages/types/src/code-runner.ts
Resolve #1499 
As title. This PR allows the usage like:
```ts
import { version } from 'vue'
const { version }  = await import('vue')
```
The old way still works:
```ts
const { version }  = await import('https://esm.sh/vue')
```
But the old way is poor in type hints.
> feat: allow importing local packages in runnable code editor

- packages/client/setup/code-runners.ts
`transfromImports` to `transformImports` in `code-runners.ts`.
> chore: fix a local function name typo

- packages/client/composables/useDragElements.ts
- packages/client/internals/DragControl.vue
If a draggable element is resized or rotated twice, dragging will stop; this PR fixes it.
> fix: condition to stop dragging

- demo/starter/slides.md
- demo/starter/snippets/external.ts
- packages/client/setup/code-runners.ts
- packages/slidev/node/vite/loaders.ts
This PR fixes the compatibility between Snippets and Monaco Runner.
````
```ts {monaco-run}
import hello from './external'
hello() // Hello from snippets/external.ts
```
````
> feat: snippets compatibility with the Monaco Runner

- packages/client/builtin/Monaco.vue
- packages/client/internals/QuickOverview.vue
- packages/client/setup/monaco.ts
The `QuickOverview` will mount all the slides, which would block the loading of the active slide.
The Monaco types will cause tons of requests, which also blocks the loading of the active slide.
Suspending these can shorten the first loading time of the active slide significantly (up to 5s on my machine)
> perf: suspend `QuickOverview` and Monaco types loading

- docs/.vitepress/config.ts
Changed the page edit link at the bottom of `docs` webpages. Previously it pointed to the mirrored repo (`slidevjs/docs`) which doesn't accept PRs. Now it points to the `docs` folder in this one.
> docs: correct page edit links

- docs/.vitepress/theme/components/Demo.vue
- docs/package.json
- pnpm-lock.yaml
fixeds #1537 
The reason for this problem is typie version @7.x up to @lasted(8.8.3).
I'm trying to a lot of typeit verison, finally found typeit@8.1.0 can run normally.
> docs: fix TypeIt error on the homepage

- packages/slidev/node/vite/markdown.ts
I am not sure why it was disabled before. But I think it would make sense to have it as the better default.
> fix: disable code interop in inline code, fix #1540

- packages/slidev/node/syntax/markdown-it/markdown-it-v-drag.ts
- packages/slidev/node/syntax/transform/code-wrapper.ts
- packages/slidev/node/syntax/transform/in-page-css.ts
- packages/slidev/node/syntax/transform/katex-wrapper.ts
- packages/slidev/node/syntax/transform/magic-move.ts
- packages/slidev/node/syntax/transform/mermaid.ts
- packages/slidev/node/syntax/transform/monaco.ts
- packages/slidev/node/syntax/transform/plant-uml.ts
- packages/slidev/node/syntax/transform/slot-sugar.ts
- packages/slidev/node/syntax/transform/snippet.ts
- packages/slidev/node/syntax/transform/utils.ts
- packages/slidev/node/vite/markdown.ts
- packages/slidev/package.json
- packages/types/src/transform.ts
- pnpm-lock.yaml
- test/__snapshots__/transform-all.test.ts.snap
- test/__snapshots__/transform.test.ts.snap
- test/_tutils.ts
- test/transform-all.test.ts
- test/transform-magic-move.test.ts
- test/transform.test.ts
> fix: use `magic-string-stack`

- README.md
- docs/.vitepress/theme/components/Environment.vue
- docs/custom/highlighters.md
- docs/guide/index.md
- docs/guide/syntax.md
- docs/guide/why.md
- docs/themes/write-a-theme.md
- packages/create-theme/template/styles/index.ts
- packages/slidev/node/vite/markdown.ts
- packages/types/src/config.ts
As described in https://github.com/slidevjs/slidev/issues/1390
This PR marks Prism.js support as deprecated by updating the docs and emitting a warning upon usage.
It will be removed in v0.50.0 (the next next breaking changes)
> docs: mark Prism.js support as deprecated

- packages/client/builtin/VClickGap.vue
> fix: `VClickGap` component

- packages/client/composables/useNav.ts
- packages/client/constants.ts
- packages/client/env.ts
- packages/client/internals/Controls.vue
- packages/client/internals/DrawingControls.vue
- packages/client/internals/DrawingLayer.vue
- packages/client/internals/DrawingPreview.vue
- packages/client/internals/NavControls.vue
- packages/client/internals/NoteDisplay.vue
- packages/client/internals/QuickOverview.vue
- packages/client/internals/Settings.vue
- packages/client/internals/SlideContainer.vue
- packages/client/internals/SlideWrapper.vue
- packages/client/internals/SlidesShow.vue
- packages/client/pages/entry.vue
- packages/client/pages/notes.vue
- packages/client/pages/overview.vue
- packages/client/pages/play.vue
- packages/client/pages/presenter.vue
- packages/client/setup/root.ts
- packages/client/styles/index.css
- packages/types/src/types.ts
- test/_tutils.ts
This PR is extracted from #1513, and it includes some harmless refactor and some small fixes.
> refactor: DOM structure

- packages/slidev/node/syntax/markdown-it/markdown-it-link.ts
- packages/slidev/node/vite/loaders.ts
- packages/slidev/node/vite/markdown.ts
- packages/slidev/package.json
- pnpm-lock.yaml
resolve https://github.com/slidevjs/slidev/issues/1551
Transform `[foo](/1)` into `<Link to="/1">foo</Link>`
*edited by KermanX*
> feat: use `<Link>` component for internal links

- packages/slidev/node/resolver.ts
I forgot that PNPM links packages, so cliRoot isn't in the user's package at all.
> This is a little bit urgent
> fix: global installation detect

- packages/slidev/node/commands/shared.ts
- packages/slidev/node/vite/loaders.ts
In #1301 the `transformIndexHtml` hook was used to inject tags to HTML head. But the tags are not injected in fact because Slidev overrides the server's logic on `index.html` and the hook was not called.
> fix: HTML head tags injection

- docs/addons/use.md
- docs/custom/global-layers.md
Added a clarifier around global-top/bottom, and linked a couple of example add-ons.
(Now in the proper repo!)
> docs: update docs to reduce confusion

- docs/guide/install.md
- packages/slidev/node/cli.ts
- packages/types/src/cli.ts
As #1597 reported, this option is not working. I don't think there is anyone using it, so it would be fine to just remove it.
> fix: remove `--watch` option in build command

- packages/client/builtin/VClick.ts
- packages/client/builtin/VClicks.ts
Because `VClick` is a wrapper of `VClicks` component, and `VClicks` has special handling for `table` element, previously, the header of the table was shown before it should be, like this:
This PR fixes this via a new `handleSpecialElements` prop in `VClicks` element to disable the special handling
> fix: `VClick` component with `table` element

- packages/client/composables/useNav.ts
This is a regression caused by #1557: pressing right arrow key on the last click of the last slide will set clicks to 0, and pressing left arrow key on the first click of the first slide will set clicks to CLICKS_MAX
> fix: navigating on the first and last click

- packages/slidev/node/cli.ts
- packages/slidev/node/vite/loaders.ts
Previously, when `data.features` changed, the browser page will get a full reload but the server isn't started. This caused some problems. For example, the Katex CSS is not loaded when user adds the first Katex code block.
This PR restarts the server when the `katex` and `monaco` features become enabled.
> fix: should restart server on feature change

- docs/guide/hosting.md
In the docs, there is the following : `In this file, replace <name_of_repo> with name_of_repo`. This is used to set the base path to the name of the repo on build. But this value set manually by the user can be retrieved from Github Actions variables.
You can find an example here : https://github.com/damienfern/talk_creer_son_twitch_personnel/
> docs(hosting): use GitHub action variable to set base url

- packages/client/env.ts
- packages/parser/src/fs.ts
- packages/slidev/node/commands/shared.ts
- packages/slidev/node/virtual/configs.ts
- packages/types/client.d.ts
Previously, the `getTitle` returns undefined, because the logic in itself is incorrect, and the `load` function in `parser/fs.ts` returns `headmatter: {title: undefined}` which prevents the default value (`"Slidev"`) of `title` from taking effect.
> fix: should render title correctly in `index.html`

- packages/client/setup/routes.ts
- packages/slidev/node/vite/extendConfig.ts
- shim.d.ts
> fix: print should work in build mode when download is on

- demo/starter/slides.md
- docs/guide/syntax.md
- packages/client/builtin/ShikiMagicMove.vue
- packages/slidev/node/syntax/transform/magic-move.ts
- packages/slidev/node/vite/markdown.ts
> feat: line numbers support in magic-move

- demo/starter/slides.md
- docs/builtin/components.md
- docs/guide/draggable.md
- packages/client/builtin/Arrow.vue
- packages/client/builtin/VDrag.vue
- packages/client/builtin/VDragArrow.vue
- packages/client/composables/useDragElements.ts
- packages/client/internals/DragControl.vue
- packages/client/modules/v-drag.ts
- packages/slidev/node/syntax/markdown-it/markdown-it-v-drag.ts
Now arrows are draggable via the `<v-drag-arrow />` component. (See demo slides page 13)
- Should there be `<Line>` and `<v-drag-line>` ?
- I think currently the cost to maintain 3 kinds of draggable elements (directive, `<v-drag>`, `<v-drag-arrow>`) is lower than coming up with a more universal draggable solution. Because these 3 ones are different in many behaviors. Not sure if there will be more draggable components in the feature.
> feat: two-way arrow and `v-drag-arrow`

- packages/client/builtin/Monaco.vue
- packages/client/setup/monaco.ts
Hi 👋 
first of all: thank you for this great tool :)
I noticed that it's not possible to configure the monaco editor via a `setup/monaco.ts` file as described at https://sli.dev/custom/config-monaco. This PR fixes that 😁
> fix(monaco): `editorOptions` from monaco setup not applied

- packages/client/internals/SlideWrapper.vue
> fix: slide layer should not cover the slide below it

- packages/slidev/node/commands/export.ts
- packages/types/src/toc.ts
> fix: exported PDF table of contents levels

- docs/custom/config-code-runners.md
Fixing some grammar/typos (singular vs. plural forms, with in front of without) in the code runner docs.
> docs: typos/grammar

- packages/slidev/node/syntax/transform/mermaid.ts
- packages/slidev/node/syntax/transform/monaco.ts
> fix: regex matching options

- packages/slidev/node/commands/server.ts
We already load and merge the vite.config.ts files from different roots, but createServer from Vite (imported as createViteServer) will load the the vite.config.ts from the project root and merge it with the provided config. This means, in particular, that plugins may end up being duplicated which can lead to various issues.
> fix: do not duplicate Vite config

- packages/vscode/src/views/annotations.ts
Old behaviour:
```
--- #2, #3, #4, #5, #6
src: ./other.md
---
```
New behaviour:
```
--- #2-6
src: ./other.md
---
```
> feat(vscode): optimize slide number with merging logic

- packages/vscode/src/composables/useDevServer.ts
This PR fixes an issue in which the "Start Dev Server" command executed with the VSCode extension can build only default "slides.md".
For building custom markdown files, the filename should be explicitly specified.
> fix(vscode): should pass entry file name to CLI

- docs/custom/index.md
- packages/client/composables/useWakeLock.ts
- packages/client/constants.ts
- packages/client/internals/SelectList.vue
- packages/client/internals/Settings.vue
- packages/client/pages/play.vue
- packages/client/pages/presenter.vue
- packages/client/state/index.ts
- packages/parser/src/config.ts
- packages/slidev/node/vite/extendConfig.ts
- packages/types/src/config.ts
- shim.d.ts
> feat: optional wake lock

- docs/guide/editors.md
- packages/vscode/package.json
- packages/vscode/src/commands.ts
- packages/vscode/src/configs.ts
- packages/vscode/src/projects.ts
- packages/vscode/src/utils/findPossibleEntries.ts
- packages/vscode/src/views/projectsTree.ts
Add `slidev.include` configuration to include files as Slidev entries when activating the extension.
> feat(vscode): `slidev.include` configuration

- packages/client/pages/overview.vue
- packages/slidev/node/commands/shared.ts
- packages/slidev/node/vite/loaders.ts
fix #1690. Removes file paths when building.
#1690 also reports some problems with chunk file names, but I can't figure out a good solution yet - Improvements to the chunking may need to be delayed.
> fix: remove filepaths when building

- docs/guide/exporting.md
- packages/slidev/node/cli.ts
- packages/slidev/node/commands/export.ts
- packages/types/src/cli.ts
resolves #1514.
This PR introduces the `--wait-until` option, so that users can skip `waitUntil: 'networkidle'` if they want, which often causes timeout.
There is also a `--wait-until` option to wait for a state before exporting each slide:
```bash
$ slidev export --wait-until none
```
Possible values:
- `'networkidle'` - (_default_) consider operation to be finished when there are no network connections for at least `500` ms. Don't use this method for testing, rely on web assertions to assess readiness instead.
- `'domcontentloaded'` - consider operation to be finished when the `DOMContentLoaded` event is fired.
- `'load'` - consider operation to be finished when the `load` event is fired.
- `'none'` - do not wait for any event.
> [!warning]
> When specifying values other than …
> feat: add `--wait-until` option for exporting

- packages/client/internals/CodeRunner.vue
- packages/client/setup/code-runners.ts
- packages/types/src/code-runner.ts
resolve #1505.
Example snippet:
```ts
import { sleep } from '@antfu/utils'
await sleep(400)
console.log('1')
await sleep(400)
console.log('2')
await sleep(400)
throw 'err!'
console.log('3')
```
Note that the runner **itself** can still be async and will be awaited. So the runner can choose whether to output or the contents in one go, or asynchronously.
> feat: support async output in code runner

- docs/custom/vue-context.md
- packages/client/index.ts
- packages/client/logic/slides.ts
resolves #1550.
New functions:
```ts
export { useIsSlideActive, onSlideEnter, onSlideLeave } from './logic/slides'
```
> feat: add slide lifetime hooks

- packages/client/composables/useClicks.ts
- packages/client/composables/useNav.ts
- packages/client/internals/ClicksSlider.vue
- packages/client/internals/SlideWrapper.vue
- packages/client/pages/presenter.vue
- packages/types/src/clicks.ts
`isMounted` represents whether the clicks elements in this slide are all mounted. After `isMounted` becomes `true`, `clicksContext.total` will represent the real value, instead of an intermediate one. This makes the clicks system much more stable - and we can fix possible bugs caused by the "intermediate state before all children are mounted" in the future.
Fix: `previewNext` displays the first click instead of the next one after refreshing.
Also fix #1678.
> fix: introduce `isMounted` state for clicks context

- demo/starter/slides.md
- docs/builtin/components.md
- packages/client/assets/logo.svg
- packages/client/builtin/PoweredBySlidev.vue
- packages/client/uno.config.ts
Inspired by sxzz's words on today's livestream. Builtin Slidev logo component and UnoCSS icon will be convenient.
<details>
<summary> Test code </summary>
```md
<br>
<br>
<br>
<PoweredBySlidev />
```
</details>
I am not very confident about the fonts and spacing.
> feat: add `PoweredBySlidev` component and `i-slidev-logo`

- packages/vscode/package.json
- pnpm-lock.yaml
- taze.config.ts
Reasons:
1. `engines.vscode` must be updated when bumping `@types/vscode` (See https://github.com/slidevjs/slidev/actions/runs/9660405919/job/26645919911)
2. Usually no new features introduced by the latest version of VSCode are required. Updating `engines.vscode` will inconvenience users using older VSCode versions.
> chore: pin `@types/vscode` to `1.89.0`

- packages/client/pages/play.vue
| Before | ![image](https://github.com/slidevjs/slidev/assets/63178754/dbed107e-b418-49b6-a151-506b8e56bdf7) |
| - | - |
| After | ![image](https://github.com/slidevjs/slidev/assets/63178754/a0c39fae-88e5-42da-9d3a-eb2e6a4875c7) |
> feat: limit `vite-error-overlay` in the slides area

- docs/guide/index.md
A minor correction: `npx` was merged into the [`npm` CLI](https://github.com/npm/cli) in 2021.
> chore: update URL of `npx` package

- docs/guide/syntax.md
Documenting the behavior described at https://github.com/slidevjs/slidev/issues/1680#issuecomment-2197852296
> docs: add example and correct usage of `[click]` & `[click:{n+1}]`

- packages/client/context.ts
- packages/client/internals/SlideWrapper.vue
- packages/client/shim-vue.d.ts
- packages/slidev/node/vite/loaders.ts
fix #1725 (i.e. close https://github.com/slidevjs/slidev/discussions/1671)
Provide frontmatter in `SlideWrapper` instead of injecting `provide(frontmatter)` to the slide markdown
> fix: frontmatter provide strategy

- docs/guide/exporting.md
- packages/slidev/node/commands/export.ts
fix #1729. The default value (`networkidle`) was missing.
> fix: default value of `--wait-for` option

- packages/slidev/node/syntax/transform/code-wrapper.ts
- test/__snapshots__/transform-all.test.ts.snap
- test/__snapshots__/transform.test.ts.snap
- test/transform-all.test.ts
close #1754.
Previously, the code block regex couldn't match
````md
```ts·
abc
```
````
(There is a space after `ts`)
> fix: code block regex

- docs/features/shiki-magic-move.md
I noticed these links while clicking around and discovering features. They currently don't link anywhere useful, so I edited them to point towards their mentioned features.
> docs: fix links in features/shiki-magic-move.md

- packages/vscode/language-server/index.ts
- packages/vscode/language-server/languagePlugin.ts
- packages/vscode/language-server/prettierService.ts
- packages/vscode/schema/frontmatter.json
- packages/vscode/schema/headmatter.json
- packages/vscode/scripts/schema.ts
- packages/vscode/syntaxes/slidev.tmLanguage.json
Fixes:
- "Scheme not found" error on my machine
- Hover message wasn't rendered as Markdown
- Prettier used to parse frontmatters as Markdown instead of YAML
- Highlight `all` inside code block attributes
- Add trailing <del>comma</del> new line to generated schemas so that ESLint won't complain (should the generated files be added to `.gitignore`?)
> fix(vscode): hover message, formatting and highlighting

- packages/parser/src/fs.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/vite/loaders.ts
- packages/slidev/node/vite/markdown.ts
- packages/types/src/options.ts
fix #1772.
This is a regression caused by #1767. In which the check of whether the processed file is the entry file was removed from the `before` hook of `unplugin-vue-markdown`.
And inside `handleHotUpdate`, `await ctx.read` was called because of #884. Unfortunately, `unplugin-vue-markdown` overrides this method [here](https://github.com/unplugin/unplugin-vue-markdown/blob/825ffc0d780f16297e48b9a27a278d7b72146408/src/index.ts#L34-L43). This causes unexpected processing of the entry file, while the client hasn't import it at all.
This PR fixes this by adding `order: 'pre'` to the loader plugin to use `await ctx.read` before `unplugin-vue-markdown`, and re-adding the checks in the `before` hook of `unplugin-vue-markdown`.
> fix: should not pass entry files to MarkdownIt

- packages/parser/src/fs.ts
- packages/slidev/node/syntax/transform/snippet.ts
- packages/slidev/node/vite/loaders.ts
- packages/types/src/types.ts
- packages/vscode/src/projects.ts
- packages/vscode/src/views/projectsTree.ts
- test/_tutils.ts
fix HMR for code snippets (`<<< path/to/snippet.ts`)
Redesigned `data.watchFiles`:
Previously, it was an array for all watched files that should trigger Slidev's `handleHotUpdate`. In `handleHotUpdate`, Slidev first **load**s the slides and compares each slide to know which slide should be updated. However, code snippets are loaded in **transform** hook. The new `data.watchFiles` is an object mapping from the watched file path to slide indexes that **must** be updated when the file is changed.
> fix: code snippets HMR

- packages/vscode/syntaxes/slidev.tmLanguage.json
fix #1801
Slidev's syntax highlighting is broken in the latest VSCode. I think this is due to https://github.com/microsoft/vscode/pull/221204.
This fix works but I don't know if it is the best way.
> fix(vscode): textmate grammar

- packages/slidev/node/virtual/slides.ts
While debugging some other issue, it appeared that error messages were consumed in some scenarios. This PR adds error logging to the console when the cached slide import fails, making it easier for others to debug their issues.
> fix: display slide import errors in client

- packages/client/composables/useDragElements.ts
- packages/slidev/node/syntax/markdown-it/markdown-it-v-drag.ts
> fix: v-drag functionality

- docs/builtin/cli.md
- docs/guide/exporting.md
- packages/slidev/node/cli.ts
- packages/slidev/node/commands/export.ts
- packages/types/src/cli.ts
PNGs are generated by taking a screenshot of the page as if it were running in a browser using Playwright. Currently, PNG exports will never be transparent and will always have the default, white, browser background regardless of if the user has removed all backgrounds using css. Playwright has an `omitBackground` property that can be added to the `.screenshot` method to remove this final browser background.
https://playwright.dev/docs/api/class-page#page-screenshot-option-omit-background
This PR adds the `--omit-background` CLI option to control the visibility of the default browser background and allow for the possibility of transparent png exports. It also adds docs for this feature
Users will still need to apply additional css styling to remove the css backgrounds from their slides in …
> feat: add CLI option to allow transparent pngs

- docs/.vitepress/addons.ts
Also, fix the link to editing the addon list file.
> docs: add slidev-addon-tldraw to addon list

- demo/starter/slides.md
- change to the correct link
- change page `More` to `more`
- typo
https://sli.dev/features/slide-scope-style
https://github.com/slidevjs/slidev/blob/e92b9e2d3faad8f7cfabc4d571194e38bae30707/demo/starter/slides.md?plain=1#L71
There is an issue with this link.
> docs: fix links and typos in features/slide-scope-style

- docs/guide/write-theme.md
Fixes a typo in the docs where `pnpm create` was incorrectly referred as `pnpm init`
> fix: typo on pnpm create command

- packages/client/index.ts
- packages/client/state/drawings.ts
- packages/client/state/shared.ts
- packages/client/state/syncState.ts
Extends `createSyncState` to allow custom external synchronization.
the goal is to solve the problem with synchronization using static builds:
* https://github.com/slidevjs/slidev/issues/855
* https://github.com/slidevjs/slidev/issues/1227
This can be a quick solution before migrating on Nuxt.
I am already working on an addon that will allow synchronization of shared and drawings states (and possibly others).
* The addon: https://github.com/Smile-SA/slidev-addon-sync
* The SSE and WS server that can be used for the synchronization: https://github.com/Smile-SA/slidev-sync-server
> feat: create extendable sync states

- packages/slidev/node/vite/extendConfig.ts
Avoid reloading the page on the first start:
```txt
17:57:56 [vite] ✨ new dependencies optimized: html-to-image
17:57:56 [vite] ✨ optimized dependencies changed. reloading
```
> fix: add `html-to-image` package to `optimizeDeps`

- README.md
- packages/create-theme/template/README.md
- packages/slidev/template.md
- packages/types/src/frontmatter.ts
- packages/vscode/schema/headmatter.json
This PR suggests fixing some dead links in several files:
* https://sli.dev/themes/use or https://sli.dev/themes/use.html → https://sli.dev/guide/theme-addon#use-theme
* https://sli.dev/themes/gallery or https://sli.dev/themes/gallery.html → https://sli.dev/resources/theme-gallery
> chore: fix dead links like `/themes`

- docs/.vitepress/showcases.ts
The old URL only works with Git tool. Fix to make it accessible via browser.
> docs: fix sourceLink of the Rust talk

- docs/.vitepress/addons.ts
Add my addon [slidev-addon-rabbit](https://github.com/kaakaa/slidev-addon-rabbit) to [Addon Gallery \| Slidev](https://sli.dev/resources/addon-gallery).
> docs: add `slidev-addon-rabbit` to addon gallery

- packages/slidev/node/commands/export.ts
> fix: `export-notes` command should wait until `networkidle`

- packages/client/setup/monaco.ts
fix #1876
<del>Not sure if this fix works. Waiting for the preview....</del> This works: https://deploy-preview-1905--slidev.netlify.app/demo/starter/15.
> fix: Monaco editor context menu in build mode

- packages/slidev/node/vite/loaders.ts
fix #1910
Facade modules like `/@slidev/slides/3` should be HMRed when it's target source module is changed
> fix: HMR on slide facades

- packages/slidev/node/syntax/transform/snippet.ts
fix #1828.
Previously, regionname was required in `// #endregion regionname`. This PR supports omitting the regionname, just like VSCode.
> fix: allow to omit region name in endregion tag in code snippets

- packages/vscode/src/composables/useFocusedSlideNo.ts
- packages/vscode/src/views/slidesTree.ts
> fix(vscode): navigating focused slides

- packages/slidev/node/vite/extendConfig.ts
> fix: do not override user-provided html files

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
When clicking on a link in the `Toc`  Component in presenter mode, it exits presenter mode unintentionally. This disrupts the presenter experience by requiring the user to re-enter presenter mode, interrupting the flow.
Modify the `TocList` component to prepend `/presenter` to each item's path when `$slidev.nav.isPresenter` is `true`.
> fix: ToC link in Presenter Mode

- packages/slidev/node/setups/preparser.ts
Currently the preparser is only called if `addons.length > 0`. If no addons are used the preparser does not work. This fixes that issue.
> fix: setup preparser correctly when no addons are used

- packages/client/constants.ts
- packages/client/internals/SlideWrapper.vue
- packages/slidev/node/setups/indexHtml.ts
close: #1663 
Apply lang attribute into page/index.html from frontmatter/headmatter.
> feat: support lang attributes

- packages/client/main.ts
fix #1925 
I was so careless and silly yesterday. 😇
> fix: should await `setupMain`

- packages/client/uno.config.ts
A temporary workaround for #1705.
> fix: add frequently missing classes to unocss safelist

- packages/client/constants.ts
- packages/client/internals/QuickOverview.vue
- packages/client/internals/SlideContainer.vue
- packages/client/internals/SlidesShow.vue
- packages/client/logic/hmr.ts
- packages/client/logic/snapshot.ts
- packages/client/package.json
- packages/client/pages/export.vue
- packages/client/state/snapshot.ts
- packages/client/state/storage.ts
- packages/parser/src/config.ts
- packages/slidev/node/vite/extendConfig.ts
- packages/types/src/frontmatter.ts
- packages/vscode/schema/headmatter.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Use the same screenshot logic from #1972 by @KermanX, remove the previous `html-to-image` approach.
- fix #1889
- fix #1883
> feat: use screen capture for slides snapshot

- README.md
- docs/custom/config-mermaid.md
- docs/features/mermaid.md
- docs/guide/syntax.md
_Mermaid.js_ is now just referenced as _Mermaid_ on their website.
> docs: update Mermaid name and URLs, fix grammar

- docs/guide/syntax.md
Hi guys,
I've just found a typo while reading the documentation for the first time. I'm new to Slidev and I'm really impressed.
Looking forward to future continued cooperation.
Cheers!
> docs: fix typo `installed` -> `install`

- packages/client/pages/export.vue
> fix(export): increase outdated browser warning's bottom margin to `2`

- docs/.vitepress/showcases.ts
I have created a presentation explaining Python for the Arabic community using the Python add-on to run Python inside the slide. this adds a step further above and beyond Jupiter notebooks. I thought that it was a good idea to spread the word in the Arabic community and announce that here.
The [slides ](https://kareimgazer.github.io/py-intro/1) is for the first episode of my Python series "Python From Zero To Hero", and it uses almost all the features of Slidev.
> docs: add "Python Zero To Hero" to showcases

- docs/guide/animations.md
The single quotes were placed incorrectly.
> docs: fix minor error with relative clicks

- docs/builtin/cli.md
- packages/slidev/node/cli.ts
- packages/slidev/node/setups/indexHtml.ts
- packages/types/src/options.ts
> feat: support base option in dev mode

- packages/client/setup/code-runners.ts
- packages/slidev/node/options.ts
- packages/slidev/node/resolver.ts
- packages/slidev/node/syntax/markdown-it/index.ts
- packages/slidev/node/syntax/markdown-it/markdown-it-katex.ts
- packages/slidev/node/vite/loaders.ts
- packages/types/src/options.ts
> feat: support KaTex in notes

- docs/custom/config-fonts.md
- packages/slidev/node/setups/indexHtml.ts
- packages/slidev/node/utils.ts
- packages/types/src/config.ts
- packages/types/src/frontmatter.ts
- packages/vscode/schema/headmatter.json
- test/__snapshots__/utils.test.ts.snap
- test/utils.test.ts
close #1977.
Integration for coollabs fonts, based on the suggestion in #1977
> feat: support coollabs as font provider

- docs/features/icons.md
This is mostly taken from UnoCSS' docs: https://unocss.dev/presets/icons#icon-customizations
> docs: explain how to install icon sets

- packages/client/composables/useHideCursorIdle.ts
- packages/client/pages/play.vue
The cursor sometimes hides after I switch to the export page.
> fix: should reshow cursor when switching out playing page

- packages/client/internals/SlidesShow.vue
The line removed in this PR was added by me, which I thought could improve the performance by limiting the number of DOM nodes. But this will cause the nodes to frequently unmount and remount. I am not sure about the best way to do this.
Also resolves #1961.
> fix: do not unmount slide too far away

- packages/slidev/node/cli.ts
> fix: visual clue when pressing `r`

- packages/client/composables/useClicks.ts
> fix: use computed for clicks initialization in `createFixedClicks`

- packages/client/builtin/VClicks.ts
> fix: allow `at` to be `0` in `<v-clicks>`

- packages/slidev/node/utils.ts
> fix: disable `jiti`'s `moduleCache`

- packages/client/internals/SlideContainer.vue
> fix: do not use `useStyleTag` in SPA slides

- docs/guide/index.md
- packages/create-app/index.mjs
Hi everyone,
I've really enjoyed using this awesome tool for quite some time, but it's always bothered me that I can't use `bun` during the setup for installing dependencies. 
Bun offers excellent performance for both execution and package management and has very high compatibility with `node` while being significantly faster. 
Anyway, here's a small PR allowing you to use `bun` as the package manager when setting up a new project
> feat: allow bun as package manager for dep installation

- docs/custom/config-unocss.md
- docs/guide/index.md
UnoCSS [Wind3 preset document](https://unocss.dev/presets/wind3) says
> [!NOTE]
> `@unocss/preset-wind` and `@unocss/preset-uno` are deprecated and renamed to `@unocss/preset-wind3`. This preset inherits from [@unocss/preset-mini](https://unocss.dev/presets/mini).
In [Configure UnoCSS docs](https://sli.dev/custom/config-unocss), the old name and link remain.
This PR fixed them.
> docs: rename `preset-uno` to `preset-wind3`

- packages/parser/src/core.ts
I went with this solution as it doesn't change the `transformSlide` function signature. Otherwise, the change would either be breaking or we need to add the SlideInfo as redundant function argument (it also contains `content` and `frontmatter`). Having the whole SlideInfo might enable more use cases, but also might have the potential for modifications that shouldn't be done.
Closes #2095.
> feat: allow to set title/level from preparser via frontmatter keys

- demo/starter/slides.md
In the `demo/starter/slides.md` file, the click event for the "Open in Editor" button should use `@click="$slidev.nav.openInEditor()"` instead of `@click="$slidev.nav.openInEditor"`!
Because the `openInEditor` method takes an optional URL string parameter. Using `@click="$slidev.nav.openInEditor"` would end up passing the $event object as the `url` parameter.
In the end, clicking the button will seem like nothing happens (only the network will fail with `/__open-in-editor?file=xxx`requests).
```ts
async function openInEditor(url?: string) {
if (!__DEV__)
return false
if (url == null) {
const slide = currentSlideRoute.value?.meta?.slide
if (!slide)
return false
url = `${slide.filepath}:${slide.start}`
}
await fetch(`/__open-in-editor?file=${encodeURIComponent(url)}`)
return true
}
```
> fix: Use `openInEditor()` instead of `openInEditor`

- docs/custom/config-vite.md
- packages/slidev/node/vite/index.ts
- packages/slidev/node/vite/userPlugins.ts
- packages/types/src/setups.ts
This would enable some advanced uses cases for me. I couldn't find any other method to access slide data in my Vite plugin so far.
> feat: allow adding Vite plugins dependent on slides data

- demo/starter/slides.md
- docs/custom/index.md
- docs/vite.config.ts
- packages/client/constants.ts
- packages/parser/src/config.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
- packages/slidev/node/setups/indexHtml.ts
- packages/slidev/package.json
- packages/types/src/frontmatter.ts
- packages/vscode/schema/headmatter.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Support Open Graph Protocol in the headmatter. Only adding support for the following attributes:
```
seoMeta:
ogTitle: Slidev Starter Template
ogDescription: Presentation slides for developers
ogImage: https://cover.sli.dev
ogUrl: https://example.com
twitterCard: summary_large_image
twitterTitle: Slidev Starter Template
twitterDescription: Presentation slides for developers
twitterImage: https://cover.sli.dev
twitterSite: username
twitterUrl: https://example.com
```
- The SEO meta tag should be visible in the view source page.
- https://github.com/slidevjs/slidev/issues/1932
> feat: support open graph protocol

- docs/custom/config-parser.md
- packages/parser/src/core.ts
- packages/types/src/types.ts
This pull request introduces a new feature to extend the functionality of the Slidev parser. The main addition is the ability to transform slide notes using a new `transformNote` function in the preparser extensions.
* [`docs/custom/config-parser.md`](diffhunk://#diff-747ec0f013ea2f8a79c740f2e4943b0fdb9f8e3b199e2a1f2b5652840da6965dR54): Added documentation for the `transformNote` function, which allows mutation of slide notes and frontmatter.
* [`packages/parser/src/core.ts`](diffhunk://#diff-9f10be93f50786b3cc60692df26b1049accf4e72b86a1ee97cc7c3111cb550a8R158-R163): Implemented the `transformNote` function to process slide notes during the parsing phase.
* [`packages/types/src/types.ts`](diffhunk://#diff-d504dca5634eaddee93d2c8d0cfad5eb813a89643e13c80f44fdf3a837b3c562R125): Updated the …
> feat(parser): transform slide notes

- packages/client/internals/SideEditor.vue
- packages/parser/src/core.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
Fixes #1579. Otherwise, the editor would load the preprocessed content and overwrite the unprocessed content.
> fix: load raw slide content in slide editor

- packages/client/composables/useHideCursorIdle.ts
Fixes #2146
With this change the timer gets cleared in two scenarios:
1. **Entering the presenter mode with `shouldHide` enabled.** Before the change the timer started in the play mode would finish after switching to the presenter mode and the cursor got stuck in the hidden mode indefinitely.
1. **When the `shouldHide` is disabled via keyboard.** In this scenario the pointer event listener isn't called, so the cursor would hide after disabling the option—this happened only once per toggle, though.
> fix: clear idle cursor timeout when disabling the option or changing to the presenter mode

- packages/slidev/node/cli.ts
Avoid duplicate keypress event listening.
> fix: add off for process.stdin keypress

- packages/client/internals/RecordingDialog.vue
- packages/client/logic/recording.ts
Currently, the recording frame rate is fixed at 15fps, with a bitrate of 8Mbps and a default resolution of 4K. 
To enhance flexibility, this pull request introduces several common frame rate and resolution options to the RecordDialog, as well as a user-defined bitrate setting.
close #1998
> feat(recording): add frame rate, resolution and bitrate controls

- packages/slidev/node/setups/indexHtml.ts
The existing code works fine for standard paths but encounters issues when handling paths containing Unicode characters.  This PR addresses the problem by encoding the paths containing Unicode characters.
fix #2154
> fix: encode entry path URI in indexHtml setup

- packages/slidev/node/vite/extendConfig.ts
Hey there! :wave: Thanks for the amazing project! :star_struck: 
This PR fixes an issue that I've run into when trying to use `@webcontainer/api` with `slidev`. The problem is that `slidev` ignores the `server.headers` configuration when serving the initial page.
After this PR, the `headers` field will now be respected for `vite.config.ts` similar to this:
```ts
import { defineConfig } from 'vite';
export default defineConfig({
server: {
headers: {
'Cross-Origin-Embedder-Policy': 'require-corp',
'Cross-Origin-Opener-Policy': 'same-origin',
},
},
});
```
For applying the headers from that field, I've followed the same logic as `vite` does for static assets. See [here](https://github.com/vitejs/vite/blob/54e0a18773be6f6c35d92db5be7f3e6159c23589/packages/vite/src/node/server/middlewares/stati …
> fix: inject headers defined in vite config

- packages/client/composables/useClicks.ts
resolve #1611 
On `shiki-magic-move` and `VSwitch`, when set `at` prop less than 1, the behavior is strange. This PR make sure the `at` prop always greater than 0, and will print a warning message on console when `at` prop less than 1.
|    *   | *   |
| ------ | ---- |
| **Before** | ![CleanShot 2025-05-30 at 15 09 12](https://github.com/user-attachments/assets/947d2e39-4da3-4721-9aac-2800a33df6bc) |
| **After**  | ![CleanShot 2025-05-30 at 15 11 53](https://github.com/user-attachments/assets/058dd6fd-7a83-460d-a46e-8af3bb2bc1fe) |
<details>
<summary>slide content {at:0}</summary>
`````md
---
theme: default
highlighter: shiki
layout: two-cols
layoutClass: gap-10
---
````md magic-move {at:0}
```js
cosnole.log('step 1')
```
```js
cosnole.log('step 2')
```
```js
cosnole.log('step 3')
``` …
> fix: make sure `at` prop is greater than 0

- packages/client/pages/presenter.vue
resolve #2192
The `clicksContext` for next slide preview should not be fixed. This will cause click system not work normally.
| *          | Inspect the `next preview` container |
| ---------- | ------------------------------------ |
| **Before** | ![before](https://github.com/user-attachments/assets/fba998f1-b9d7-4322-8a51-d2a38e1192d3)|
| **After**  | ![after](https://github.com/user-attachments/assets/871b29ee-09c8-47ae-8176-babbbc299ed0) |
> fix: next slide preview

- packages/client/composables/useNav.ts
I have encountered this issue in my own PPT project (which can be a reproduction repo): https://github.com/ShenQingchuan/vue-vine-ppt-2025
But it'll be OK after restarting the slidev dev server.
I think it might be caused by my Vue Vine plugin using in setup/main.ts, maybe it's applied before Vue Router and the router instance was not initialized at that moment? I'm not quite sure ...
But I've tried and approved that this line of change works as expected, which is adding optional chain operators.
fix #2047
> fix: add optional chain to prevent nullish broken

- packages/vscode/README.md
`... developers who uses VS Code` -> `... developers who use VS Code`
> Fix grammar in VS Code extension `README.md`

- .github/workflows/smoke.yml
- demo/starter/slides.md
- docs/features/og-image.md
- docs/features/seo-meta.md
- docs/package.json
- package.json
- packages/client/composables/useNav.ts
- packages/client/package.json
- packages/create-app/package.json
- packages/create-app/template/package.json
- packages/create-theme/package.json
- packages/create-theme/template/package.json
- packages/parser/package.json
- packages/slidev/node/commands/build.ts
- packages/slidev/node/setups/indexHtml.ts
- packages/slidev/package.json
- packages/types/package.json
- packages/vscode/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Hi Slidev maintainers.
Thank you so much for your amazing work on Slidev.
I absolutely love this project!
This is my first feature implementation PR for Slidev, so please let me know if there's anything that needs improvement or if I'm causing any trouble.
I'm happy to make any necessary changes.
Currently, Slidev users need to manually create og-images for social media sharing.
The existing workflow requires:
- Export first slide as PNG
- Run `slidev export --format png --range 1` to generate first slide image
- Rename and move file
- Rename `01.png` to `og-image.png` and place in appropriate location
- Host image somewhere
- Upload to CDN, GitHub, or image hosting service
- Configure URL in frontmatter
```yaml
seoMeta:
ogImage: https://example.com/og-image.png
```
```yaml
---
seoMeta: …
```
> feat: auto gen og

- packages/vscode/package.json
- packages/vscode/src/index.ts
- packages/vscode/src/lmTools.ts
Register some `lm.tools`. e.g. `getSlideContent`
Blocked by #2207. Related to #2132.
- Do more testing
- More tools
> feat(vscode): add language model tools

- docs/guide/animations.md
The description of the first example was extended for clarification. The description of the second example seemed to be wrong and was thus changed.
> [DOC] adapt description of enter & leave

- packages/vscode/schema/headmatter.json
https://sli.dev/guide/animations#slide-transitions says that
> You can enable it by setting the transition frontmatter option.
which implies that not setting this option disables slide transitions, so it should not be considered a required property of the Headmatter in schema.
> fix: transition should be optional in schema

- packages/slidev/node/commands/build.ts
auto generated open graph image respect : 
* `--dark` flag
* `--timeout` option
Closes #2265
> feat: auto generated open graph image respect options

- docs/.vitepress/addons.ts
- packages/vscode/schema/headmatter.json
I created https://github.com/whitphx/slidev-addon-window-mockup so plz let me add it to the gallery.
> Add Window Mockup addon to the addon gallery

- packages/slidev/node/setups/indexHtml.ts
- packages/vscode/src/composables/useServerDetector.ts
this had been troubling me for a bit
you may have had a reason for using `charset` that I'm not aware of, however!
> fix(slidev,vscode): use `property` for slidev meta entry in head

- packages/client/builtin/ShikiMagicMove.vue
- packages/parser/src/config.ts
- packages/types/src/frontmatter.ts
- packages/vscode/schema/headmatter.json
Added copy button support for Shiki Magic Move code block.
Add new configuration for slides - `magicMoveCopy`:
- `false`: Disable copy button
- `'final'`: Show copy button only on the final step
- `true`/`'always'`: Show copy button on all steps (default)
Copy button in magic move code block respects the global `codeCopy` setting (if `codeCopy` is disabled, the magic move copy button will always be hidden) and it copies the current step's code content.
Hope this helps!
Closes #2255
> feat: add copy button for Shiki Magic Move code block
