slidevjs/slidev

- packages/create-theme/template/_gitignore
I'm tired of adding config files to gitignore every time
> chore(create-app): update gitignore for Intellij IDE

- docs/guide/why.md
I was reading through the documentation for this really exciting project, and I noticed a minor typo in the first section. I figured I'd submit a proposed change just to bring it to your attention. Hopefully that's helpful.
> chore: typo

- docs/.vitepress/themes.ts
Since the theme is still in development, this PR can also be merged at a later point in time.
> docs(themes): add Vercel theme

- docs/.vitepress/themes.ts
A simple, light and elegant theme for Slidev, combined together with creative layouts, custom components & fonts
NPM Package: https://www.npmjs.com/package/slidev-theme-light-icons
GitHub Repo: https://github.com/lightvue/slidev-theme-light-icons
> docs(themes): add Light-icons theme

- packages/client/logic/shortcuts.ts
> feat: add page up and page down as shortcuts

- packages/create-app/index.js
> fix(create-app): trim package name

- packages/client/internals/Editor.vue
- packages/client/internals/Play.vue
- packages/client/internals/Presenter.vue
- packages/client/logic/shortcuts.ts
- packages/client/state/index.ts
fix for issue: https://github.com/slidevjs/slidev/issues/197
> fix: fullscreen shortcut

- packages/slidev/node/plugins/loaders.ts
- packages/slidev/node/utils.ts
- test/utils.test.ts
Fix bugs in the following screenshot:
> fix: remove html tags in title

- .github/ISSUE_TEMPLATE/bug_report.md
I guess articles are needed :sweat_smile:,
> chore: fix typo issue template

- demo/composable-vue/package.json
- packages/client/logic/nav.ts
- packages/client/modules/directives.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
export add a flag `everyClicks`
use `slidev export --everyClicks` export pages for every clicks
> feat(cli, client): export pages for every clicks

- packages/client/internals/Presenter.vue
- packages/client/setup/root.ts
- packages/parser/src/core.ts
- packages/types/src/types.ts
- test/__snapshots__/parser.test.ts.snap
> feat: add titleTemplate option

- packages/create-app/template/slides.md
- packages/slidev/node/plugins/markdown.ts
- packages/slidev/package.json
- pnpm-lock.yaml
> feat: add markdown footnote support

- packages/client/internals/NoteEditor.vue
- packages/client/internals/Presenter.vue
> fix: fix speaker note layout

- packages/client/internals/Editor.vue
Loving the built-in editor writing back to the filesystem, thought I'd give it some polish :)
> chore: fix pluralization of "notes" in editor

- packages/client/internals/RecordingDialog.vue
Mentioned in https://github.com/slidevjs/slidev/issues/358
> fix: small typo

- packages/client/layouts/iframe-left.vue
- packages/client/layouts/iframe-right.vue
- packages/client/layouts/iframe.vue
> feat: introduce frame layouts

- packages/slidev/node/plugins/extendConfig.ts
> fix: public path when using globally

- packages/slidev/node/plugins/extendConfig.ts
> fix: add katex to global fs allow list

- packages/slidev/node/options.ts
> fix: userRoot in nested directory

- packages/client/index.html
- packages/parser/src/config.ts
- packages/slidev/node/common.ts
- packages/slidev/node/options.ts
- packages/types/src/config.ts
- test/__snapshots__/parser.test.ts.snap
Fix https://github.com/slidevjs/slidev/issues/420
> feat: support custom favicon

- packages/slidev/node/export.ts
> docs: update error message on export error

- demo/composable-vue/components/NumBox.vue
- packages/client/internals/MenuButton.vue
- packages/client/internals/RecordingDialog.vue
- packages/client/internals/SelectList.vue
> fix: defineEmits bad argument (#450)

- packages/client/iframes/monaco/index.ts
Fix CSS injection and limited XSS bug
You can view the security vulnerability report at https://huntr.dev/bounties/cf6d24dd-2497-498a-b0ab-27c9329a934e/
This report is private and only accessible to maintainers with write permissions on this repository.
> fix: prevent XSS

- packages/client/internals/SlidesOverview.vue
> fix: on show overview drawing layer may behind wrapper in some case

- demo/starter/package.json
- packages/client/internals/RecordingDialog.vue
- packages/client/logic/recording.ts
> feat: support mp4 when recording

- packages/client/internals/NavControls.vue
- packages/slidev/node/plugins/loaders.ts
I have a component that needs some buttons, and although I can put the buttons in the component, it only shows up in the slides wrapper and changes size as the wrapper resize. So I want to put these buttons into nav controls.
> feat: custom nav controls

- packages/slidev/node/plugins/markdown.ts
Fixes https://github.com/slidevjs/slidev/issues/525
> fix: scoped style

- packages/client/logic/recording.ts
Fixes https://github.com/slidevjs/slidev/issues/535
> fix: download the video if the capture stream is stopped

- packages/slidev/node/build.ts
> fix: build slides in nest folder

- packages/client/logic/nav.ts
- packages/parser/src/config.ts
- packages/slidev/node/build.ts
- packages/slidev/node/cli.ts
- packages/types/src/config.ts
- test/__snapshots__/parser.test.ts.snap
possible implementation for https://github.com/slidevjs/slidev/issues/533
+ fix typo
>  feat: allow specifying export filename in the frontmatter

- .gitpod.yml
- .vscode/extensions.json
https://github.com/johnsoncodehk/volar/issues/1124
> chore: update volar extension id

- packages/client/builtin/Mermaid.vue
- packages/client/internals/ShadowRoot.vue
Fixes https://github.com/slidevjs/slidev/issues/564
> fix: put mermaid graphs in a shadow root to avoid duplicate ids

- packages/client/builtin/Link.vue
Fixes https://github.com/slidevjs/slidev/issues/561
> fix: error when using numbers in link component

- packages/slidev/node/plugins/loaders.ts
Fixes https://github.com/slidevjs/slidev/issues/571
> fix:  context in classical vue component

- packages/client/internals/DrawingLayer.vue
Fixes https://github.com/slidevjs/slidev/issues/534 and https://github.com/slidevjs/slidev/issues/504
> fix: drawings when using touch devices

- packages/slidev/node/plugins/loaders.ts
Fixes https://github.com/slidevjs/slidev/issues/581
> fix: error when using components returning only a render function

- packages/client/constants.ts
- packages/client/internals/Presenter.vue
- packages/client/internals/PrintSlideClick.vue
- packages/client/internals/SlideWrapper.ts
- packages/client/internals/SlidesOverview.vue
- packages/client/internals/SlidesShow.vue
Fixes https://github.com/slidevjs/slidev/issues/585
> feat: add slide route provider

- packages/client/builtin/Mermaid.vue
Change mermaid theme when switching between light and dark
> feat(mermaid): default dark theme, close #599

- packages/parser/src/core.ts
Fixes https://github.com/slidevjs/slidev/issues/424
> fix: when slide content is only a note (and last.index = 0)

- packages/slidev/node/addons.ts
should fix https://github.com/slidevjs/slidev/issues/399
> fix: error with global installation (when no package.json)

- packages/client/internals/NoteEditor.vue
- packages/client/internals/NoteStatic.vue
- packages/client/internals/NoteViewer.vue
- packages/client/internals/Presenter.vue
- packages/client/routes.ts
- packages/slidev/node/plugins/loaders.ts
Fixes https://github.com/slidevjs/slidev/issues/614
> fix: display notes for static builds (no edition)

- packages/slidev/node/cli.ts
Fixes https://github.com/slidevjs/slidev/issues/622
> fix: display remote info compatibility with node 18

- packages/slidev/node/build.ts
- packages/slidev/node/common.ts
- packages/slidev/node/plugins/loaders.ts
- packages/slidev/node/plugins/windicss.ts
- packages/slidev/node/server.ts
fixes https://github.com/slidevjs/slidev/issues/415
> feat: extend vite config from themes and addons

- packages/create-app/template/_npmrc
/!\ I haven't actually tested this PR, I've made the edit from GitHub UI based on pnpm error message, see #630 
Closes #630
> Auto install peer deps with pnpm

- packages/client/modules/directives.ts
I encontered a situation that clicks order map with undefined key. I fixed this bug.
> fix(animation): order map key undefined

- demo/starter/package.json
- demo/starter/slides.md
- packages/client/internals/PresenterPrint.vue
- packages/client/routes.ts
- packages/slidev/node/cli.ts
- packages/slidev/node/export.ts
> feat: allow to export presenter notes

- packages/client/internals/PresenterPrint.vue
Details in the PR code comments
> feat: improve print margin for notes export

- packages/client/internals/Presenter.vue
- packages/client/internals/SlidesOverview.vue
> fix: overview and presenter's next need apply theme variables, fix #746

- packages/client/layouts/iframe-left.vue
- packages/client/layouts/iframe-right.vue
This works for me, will fix #777
> feat(layouts): scale iframe-left and iframe-right

- packages/client/styles/code.css
- packages/slidev/node/plugins/markdown-it-shiki.ts
Fixes https://github.com/slidevjs/slidev/issues/810
Fixes https://github.com/slidevjs/slidev/issues/799
> fix(shiki): replace pattern to match new version of shiki + fix scrollbars styles

- packages/client/internals/NavControls.vue
- packages/client/logic/drawings.ts
Fixes https://github.com/slidevjs/slidev/issues/732
> fix: enable drawings in presenter controls if drawings.presenterOnly

- packages/client/styles/layouts-base.css
Fixes https://github.com/slidevjs/slidev/issues/834
> fix: styles for rtl languages

- packages/client/builtin/Toc.vue
- packages/client/builtin/TocList.vue
- packages/client/composables/useNav.ts
- packages/client/logic/nav.ts
- packages/slidev/node/export.ts
- packages/types/src/index.ts
- packages/types/src/toc.ts
Fixes https://github.com/slidevjs/slidev/issues/842
> fix: pdf toc when using with-clicks option

- packages/client/layoutHelper.ts
Fixes an issue where the color check always falls as it checked if the color value is a HEX value and RGB. This PR changes it so that it can be a HEX or RGB value.
> fix: isColor check in the layout helper

- packages/slidev/node/plugins/preset.ts
This would allow the user to disable the default css frameworks
> fix: allow user to opt-out the css framework, close #880

- cypress/e2e/examples/basic.spec.ts
- packages/client/internals/SlidesShow.vue
- packages/client/styles/layouts-base.css
Fixes https://github.com/slidevjs/slidev/issues/873
> fix: global top/bottom component styles

- packages/create-theme/template/.vscode/extensions.json
add vscode extension recommendation for [antfu.slidev](https://marketplace.visualstudio.com/items?itemName=antfu.slidev)
> feat: provide vscode extension recommendation for antfu.slidev

- packages/client/setup/root.ts
Fixes https://github.com/slidevjs/slidev/issues/875
> fix: broken navigation when multiple viewer tabs are open

- packages/slidev/node/plugins/loaders.ts
Fixes https://github.com/slidevjs/slidev/issues/884
> fix: too fast HMR

- packages/slidev/node/cli.ts
Commands that now accept multiple entry files:
* build
* format
* export
* export-notes
Works like this:
```bash
slidev export slides/1.md slides/2.md
```
Or by using terminal wildcards for example:
```bash
slidev export slides/*.md
```
We need to discuss the following points:
1. Some option arguments are only compatible with one entry file.
Like `output` for `export` end `export-notes`.
And like `base` for `build`.
Maybe we should not take into account these options when `entry.length > 1`.
2. Currently when building with multiple entry files, it will create a subfolder in the `dist` directory for each entry file.
For example `slidev export slides1.md slides2.md` will generate two build folders `dist/slides1` and `dist/slides2`.
But because some files are the same between the builds …
> feat: update cli to accept multiple entry files

- packages/client/composables/useContext.ts
- packages/client/composables/useNav.ts
- packages/client/composables/useNavClicks.ts
- packages/client/constants.ts
- packages/client/internals/PrintSlide.vue
- packages/client/modules/context.ts
- packages/client/shim.d.ts
Fixes https://github.com/slidevjs/slidev/issues/907
> fix: build and typescript errors

- packages/slidev/node/plugins/extendConfig.ts
Fixes https://github.com/slidevjs/slidev/issues/902
> fix: public relative directory

- cypress/e2e/examples/basic.spec.ts
- cypress/fixtures/basic/slides.md
- packages/client/builtin/VClicks.ts
- packages/client/modules/directives.ts
Fixes https://github.com/slidevjs/slidev/issues/557 https://github.com/slidevjs/slidev/issues/362
> feat: v-clicks depth parameter

- packages/client/modules/directives.ts
Fixes https://github.com/slidevjs/slidev/issues/924
> fix: v-after with relative value

- packages/slidev/node/plugins/extendConfig.ts
Fixes https://github.com/slidevjs/slidev/issues/932
> fix: allow vite config override

- packages/client/builtin/CodeBlockWrapper.vue
- packages/client/styles/code.css
> feat: more intelligent code highlight autoscrolling

- demo/starter/README.md
A tiny correction to the doc as titled.
> docs: broken link to starter README

- packages/create-app/template/package.json
Resolves `pnpm install` error
close https://github.com/slidevjs/slidev/issues/975
> fix(create-app): pnpm install error

- demo/starter/slides.md
- packages/client/internals/PresenterPrint.vue
- packages/client/internals/PrintContainer.vue
- packages/client/internals/SlidesOverview.vue
- packages/slidev/node/plugins/loaders.ts
close #1003
close #974
resolve #970
> feat!: remove the end slide

- packages/client/composables/useNav.ts
- packages/client/logic/nav.ts
> fix: broken variable `$slidev.nav.total` by 82e6e21.

- packages/slidev/node/plugins/loaders.ts
See [this comment](https://github.com/slidevjs/slidev/issues/816#issuecomment-1437844481).
> fix: Toc rendering incorrectly w/ disabled slides

- packages/client/styles/layouts-base.css
> fix: mono font css not applied for code with unocss.

- packages/client/builtin/AutoFitText.vue
- packages/client/builtin/Mermaid.vue
- packages/client/composables/useNav.ts
- packages/client/logic/nav.ts
- packages/parser/src/utils.ts
- packages/slidev/node/plugins/loaders.ts
- packages/slidev/node/plugins/markdown-it-katex.ts
> fix: `arrow-right` on Navigation Bar disabled at slide page -2.

- packages/client/builtin/VClicks.ts
> fix: comment breaking VClicks

- packages/client/logic/nav.ts
> fix: make swiping easier on tablets, fix #1068

- packages/create-app/template/netlify.toml
From version `14` to `18` (lts).
close #1145
> fix: update the Node.js version in the Netlify configuration

- packages/types/index.d.ts
> fix: rexport types

- packages/slidev/node/plugins/preset.ts
- packages/slidev/node/server.ts
> fix: server.ts reads custom components from userRoot

- packages/slidev/node/export.ts
Currently metadata (title, keywords, etc) and ToC are added to generated PDF only when it is produced by export command *without* `--per-slide` switch.
However, sometimes default exporting produces unsatisfactory results (like e.g. in https://github.com/slidevjs/slidev/issues/1154), so then one want to use `--per-slide` to generate PDF slower, but without some glitches, but also would like to get metadata in.
This pull requests extracts code for generating metadata and ToC to helper functions and calls them from both pdf generation functions.
> feat: add metadata and TOC to PDF generated with `--per-slide`

- packages/client/internals/IconButton.vue
Fix warning message caused by #1294
> fix: warning about `defineProps`

- packages/slidev/node/cli.ts
- packages/slidev/node/server.ts
> fix: fix Vue production mode breaking PDF Export (#1245)

- cypress/e2e/examples/basic.spec.ts
This PR tries to fix the failed Cypress tests.
> test: fix Cypress tests

- packages/client/builtin/Monaco.vue
- packages/client/builtin/ShikiMagicMove.vue
- packages/client/modules/mermaid.ts
> fix: importing `lz-string`

- packages/client/builtin/Mermaid.vue
This PR make the output of the Mermaid rendering error better
> fix: Mermaid rendering error report

- packages/slidev/node/plugins/loaders.ts
> fix: dynamic slide info index

- tsconfig.json
update the tsconfig.json to resolve the `packages/types` error
```json
"types": [
"vite"
]
```
close #1381
> chore: fix the declare module vite error

- docs/addons/use.md
- docs/addons/write-an-addon.md
- docs/builtin/components.md
- docs/builtin/layouts.md
- docs/custom/config-monaco.md
- docs/custom/config-parser.md
- docs/custom/config-shortcuts.md
- docs/custom/config-unocss.md
- docs/custom/config-vite.md
- docs/custom/directory-structure.md
- docs/custom/fonts.md
- docs/custom/global-layers.md
- docs/custom/index.md
- docs/custom/vue-context.md
- docs/guide/animations.md
- docs/guide/drawing.md
- docs/guide/exporting.md
- docs/guide/faq.md
- docs/guide/hosting.md
- docs/guide/index.md
- docs/guide/install.md
- docs/guide/syntax.md
- docs/guide/why.md
- docs/themes/use.md
- docs/themes/write-a-theme.md
This PR contains some (random) doc fixes.
Grammar and typo fixes are suggested by Grammarly, and I tried to avoid unnecessary fixes and make the fixes right.
> docs: update

- docs/guide/animations.md
It seems that there are some issues in the documentation.
> docs: fix `animations.md`

- docs/guide/syntax.md
Closes: https://github.com/slidevjs/slidev/issues/1371
> feat: add a guide to enabling chemical equations

- .github/workflows/smoke.yml
- scripts/remove-deps.mjs
- scripts/remove-overridden-deps.mjs
As title.
GitHub action's native functions are too limited, so I have to add a new JS to remove overridden deps.
> fix: smoke test CI when releasing a new version

- packages/slidev/node/virtual/slides.ts
> fix: log error when slide loading failed

- packages/client/composables/useViewTransition.ts
fix https://github.com/slidevjs/slidev/issues/1415
> fix: view-transition not working when switching slides quickly

- docs/builtin/components.md
> docs: add `SlidevVideo` documentation

- docs/custom/index.md
- docs/guide/syntax.md
- packages/parser/src/config.ts
- packages/slidev/node/vite/markdown.ts
- packages/types/src/config.ts
Resolve https://github.com/slidevjs/slidev/issues/1428
> feat: option `twoslash` to disable twoslash

- packages/client/internals/SlidesShow.vue
- packages/client/pages/print.vue
- packages/client/setup/main.ts
> fix: Twoslash popover not shown in print mode

- demo/starter/slides.md
- docs/guide/syntax.md
fix typo in syntax.md and slides.md
> docs: fix typo

- packages/client/composables/useSlideInfo.ts
> fix: use static slide info in build mode

- packages/client/pages/print.vue
As title.
Related chat: https://discord.com/channels/851817370623410197/855377989067604018/1220958652194885722
> fix: avoid trailing blank page in exported PDF

- docs/custom/index.md
- packages/client/composables/useClicks.ts
- packages/client/composables/useNav.ts
- packages/client/constants.ts
- packages/client/internals/ClicksSlider.vue
- packages/client/internals/PrintSlide.vue
- packages/types/src/types.ts
resolve https://github.com/slidevjs/slidev/issues/1452
> feat: add `clicksStart` option in page frontmatter

- docs/builtin/layouts.md
> docs: correct image paths

- docs/custom/highlighters.md
> docs: add note about Magic Move with transformers

- packages/slidev/node/syntax/transform/code-wrapper.ts
> fix: support CRLF for magic move

- packages/client/internals/MenuButton.vue
> fix: text color in `MenuButton` component

- docs/guide/exporting.md
Remove a duplicate part and fix typos.
> docs: update /guide/exporting page

- packages/vscode/package.json
- packages/vscode/src/utils/findPossibleEntries.ts
> feat(vscode): add menu button for `add-entry` command

- packages/vscode/src/views/annotations.ts
- packages/vscode/src/views/foldings.ts
resolves https://github.com/slidevjs/slidev-vscode/issues/22.
| Before | After |
| - | - |
| ![image](https://github.com/slidevjs/slidev/assets/63178754/c54fe30a-a66e-4caa-a4d9-5343ae3faf97) | ![image](https://github.com/slidevjs/slidev/assets/63178754/ddcc7969-9119-4af1-a6c5-ecb7e79ba46e) |
| ![image](https://github.com/slidevjs/slidev/assets/63178754/ba7caec6-298d-4251-a7ef-90ed218c2bc2) | ![image](https://github.com/slidevjs/slidev/assets/63178754/70f4e5bf-bf02-41c0-9c34-f239a57d8ca0) |
> feat(vscode): update annotations and foldings

- .gitignore
- demo/starter/slides.md
- docs/custom/index.md
- docs/guide/exporting.md
- docs/guide/install.md
- docs/guide/why.md
- packages/create-theme/template/example.md
- packages/slidev/node/cli.ts
- packages/slidev/node/commands/export.ts
- packages/slidev/package.json
- packages/slidev/template.md
- pnpm-lock.yaml
resolves #1594.
Slides in the exported PPTX are images.
Also fixes #1599
> feat: export to PPTX

- packages/client/env.ts
- packages/client/internals/QuickOverview.vue
- packages/client/logic/slides.ts
> fix: link href prefix

- packages/client/internals/Goto.vue
Fixes horizontal overflow (horizontal scrollbar on chrome)
Fixes layout for large slide numbers
> fix: Goto layout

- packages/client/pages/404.vue
- packages/client/setup/routes.ts
> feat: add 404 page

- packages/client/logic/slides.ts
- packages/client/pages/overview.vue
> fix: navigation in hash route

- CONTRIBUTING.md
- README.md
Minor updates to the documentation at the root of the repository. This PR resolves typos and/or corrects small grammatical issues.
> docs: typos

- packages/client/builtin/ShikiMagicMove.vue
> fix: update magic-move step index after page reload

- packages/client/composables/useDrawings.ts
- packages/client/state/drawings.ts
> fix: drawings should appear after build

- packages/slidev/node/vite/loaders.ts
> fix: layout loading priority

- docs/package.json
- pnpm-lock.yaml
- taze.config.ts
> docs: pin `typeit` to `v8.1.0`

- packages/client/internals/NoteDisplay.vue
fix #1680
- Performance improved
- Edge cases fixed （below are expected behavior):
| ![image](https://github.com/slidevjs/slidev/assets/63178754/7d1fe345-48ff-4e8d-adea-963eda60bd51) | ![image](https://github.com/slidevjs/slidev/assets/63178754/f7ca3ff6-63bd-4d07-87aa-4b3cf9797b38) |
| -- | -- |
> fix: notes highlighting algorithm

- demo/starter/slides.md
| **Before** | ![image](https://github.com/slidevjs/slidev/assets/63178754/a3ed0f96-93fc-4f10-b0d7-f5ea9e9e922e) |
| - | - |
| **After** | ![image](https://github.com/slidevjs/slidev/assets/63178754/4ed088d1-cb9f-4fb7-ac4f-7e7e2fc89e5b) |
> chore: update latex equation in demo slides

- .github/workflows/autofix.yml
- packages/client/setup/main.ts
It works now, as you can see in the commits in this PR. However, there is still a question: should autofix be automatically committed to the main branch? (Currently enabled).
> ci: fix autofix.ci

- .github/workflows/smoke.yml
fix timeout problem.
At first, I though there are some useless steps. But it turned out that all the steps in the test job are necessary.
> ci: fix test job in smoke.ci

- packages/client/internals/ShikiEditor.vue
- packages/client/internals/SideEditor.vue
- smaller editor margin
- fix interaction when appending new line
- fix interaction when clicking inside the editor but outside the text
> fix: side editor styles and interacation

- docs/.vitepress/themes.ts
Mint theme for slidev
NPM: https://www.npmjs.com/package/slidev-theme-mint
GitHub: https://github.com/alfatta/slidev-theme-mint
Theme demo: https://slidev-theme-mint.netlify.app
> docs: add slidev-theme-mint theme

- .github/workflows/smoke.yml
ref https://github.com/pnpm/action-setup/issues/135
> ci: upgrade `pnpm/action-setup`

- netlify.toml
- scripts/demo.mjs
- fix OOM
- build `vue-runner` demo
> docs: fix docs build

- packages/slidev/node/setups/shiki.ts
fix #1786
> Netlify deployment seems to fail because UnoCSS's webfont
> fix: shuold cache Shiki setup result

- packages/client/builtin/Monaco.vue
> fix(monaco-diff): should disable `useInlineViewWhenSpaceIsLimited`

- docs/builtin/cli.md
- docs/builtin/components.md
- docs/custom/config-context-menu.md
- docs/custom/directory-structure.md
- docs/guide/animations.md
- docs/guide/exporting.md
- docs/guide/faq.md
- docs/guide/global-context.md
- docs/guide/hosting.md
- docs/guide/syntax.md
- docs/guide/write-addon.md
These are the problems I found when translating to Chinese.
> docs: minor fixes

- docs/.vitepress/showcases.ts
> docs: Add a showcase at the PyCon APAC 2023 (2023-10-28)

- packages/client/composables/useWakeLock.ts
> fix: `useWakeLock` causing infinite loop

- docs/guide/exporting.md
see https://github.com/slidevjs/slidev/issues/1872
@KermanX 👋🏽
> docs: add broken emoji troubleshooting to exporting.md

- packages/client/setup/monaco.ts
https://shiki.style/packages/monaco
> fix: automatially register languages highlighted by Shiki to Monaco Editor

- demo/starter/slides.md
- docs/custom/index.md
- packages/client/constants.ts
- packages/client/internals/QuickOverview.vue
- packages/client/internals/SlideContainer.vue
- packages/client/logic/snapshot.ts
- packages/client/package.json
- packages/client/state/snapshot.ts
- packages/parser/src/config.ts
- packages/parser/src/core.ts
- packages/parser/src/fs.ts
- packages/slidev/node/integrations/snapshots.ts
- packages/slidev/node/vite/serverRef.ts
- packages/types/src/frontmatter.ts
- packages/types/src/types.ts
- packages/vscode/schema/headmatter.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- test/__snapshots__/parser.test.ts.snap
This PR adds an experimental flag `overviewSnapshots` that allows to take a snapshot of a slide to display in the quick overview, to improve the performance.
> feat: support snapshoting overview

- packages/client/pages/overview.vue
This PR adds Chinese character set for word counting and modify wordCount function
close #1845
> fix: Chinese character counting error in overview page (#1845)

- packages/slidev/node/syntax/transform/code-wrapper.ts
- packages/slidev/node/syntax/transform/snippet.ts
> fix: allow to omit region name in endregion tag in code snippets

- docs/.vitepress/addons.ts
- docs/.vitepress/theme/components/AddonInfo.vue
- docs/.vitepress/theme/components/ThemeInfo.vue
- docs/.vitepress/themes.ts
> docs: update gallery styles

- packages/slidev/node/cli.ts
- packages/slidev/node/options.ts
- packages/types/src/options.ts
> fix: `--download` option should affect `getDefine`

- packages/client/composables/useViewTransition.ts
close #1930 
Possibly a breaking change?
> fix: prevent view-transition in the same slide

- scripts/pack.mjs
pnpm changed its console output format
> ci: fix pack.mjs

- docs/resources/learning.md
Japanese language study articles have been created and added to the Learning Resources page.
> docs: Add link to Learning Resources

- docs/.vitepress/addons.ts
> docs: add `slidev-addon-tikzjax` to addon gallery

- CONTRIBUTING.md
- docs/features/remote-access.md
- docs/guide/exporting.md
- docs/guide/index.md
- docs/guide/write-theme.md
- packages/create-app/template/README.md
To inform users that NPM is not recommended.
> docs: PNPM as default package manager

- docs/features/vscode-extension.md
- packages/vscode/package.json
- packages/vscode/src/composables/useDevServer.ts
- packages/vscode/src/configs.ts
As title.
The docs mentioned the `--base` option, which is implemented in #2028.
> feat(vscode): allow to customize dev command

- packages/vscode/package.json
- packages/vscode/src/commands.ts
- packages/vscode/src/views/slidesTree.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- taze.config.ts
It seems that VSCode has made several breaking changes🥲. This PR fixes the problems that I found.
除夕快乐！🎆
> fix(vscode): project tree commands

- docs/features/mdc.md
> Fixing wrong link in mdc.md

- packages/slidev/node/cli.ts
- packages/slidev/node/commands/build.ts
- packages/slidev/node/commands/export.ts
> fix: markdown format export

- packages/client/setup/routes.ts
> fix: add password guard to entry, overview and print pages

- packages/slidev/node/vite/components.ts
> fix: do not exclude node_modules when searching components

- packages/slidev/node/cli.ts
- packages/slidev/node/utils.ts
- packages/slidev/node/vite/loaders.ts
> fix: theme ejection

- docs/guide/index.md
- packages/client/pages/presenter.vue
> fix: preview next clicks count

- docs/features/mdc.md
This MDC Syntax url link I found while reading the docs is not accurate enough, so I'll post a PR by the way.
> docs: update features/mdc.md

- packages/client/internals/FormCheckbox.vue
`opacity: 0.1` should be `opacity-10`.
> fix: opacity of `FormCheckbox`

- docs/.vitepress/config.ts
- docs/custom/config-vite.md
- docs/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Added support for section generation in `llms.txt`, now sections like in your sidebar will be generated (except for the "**Features**" section)
Result:
```markdown
> Presentation slides for developers
- [Why Slidev](/guide/why.md)
- [Syntax Guide](/guide/syntax.md)
- [User Interface](/guide/ui.md)
- [Animation](/guide/animations.md)
- [Theme and Addons](/guide/theme-addon.md)
- [Components in Slides](/guide/component.md)
- [Slide Layout](/guide/layout.md)
- [Exporting](/guide/exporting.md)
- [Building and Hosting](/guide/hosting.md)
- [FAQ](/guide/faq.md)
- [Global Context](/guide/global-context.md)
- [Writing Layouts](/guide/write-layout.md)
- [Writing Themes](/guide/write-theme.md)
- [Writing Addons](/guide/write-addon.md)
- [Directory Structure](/custom/directory-structure.md)
- …
```
> docs: generate sections in `llms.txt`

- docs/guide/index.md
just a tiny cleanup now that a fix for that was landed
> docs: simplify deno cli command

- packages/slidev/node/setups/indexHtml.ts
> fix(slidev/cli): #2230 indexHtml meta

- demo/starter/slides.md
- packages/slidev/node/vite/index.ts
- packages/slidev/node/vite/patchMonacoSourceMap.ts
- packages/vscode/schema/headmatter.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Monaco missing sourcemap warning: https://github.com/microsoft/monaco-editor/issues/4712 (should not have been closed)
- fix #2280
> fix: avoid errors and warnings that were unfriendly to starters
